export const TOP_VISUAL_ARTICLE_SLUGS = [
  "ibs-digestive-issues",
  "conjunctivitis-pink-eye",
  "medical-certificate-carers-leave",
  "shingles",
  "acid-reflux-gerd",
  "ahpra-registered-doctor-meaning",
  "amoxicillin-guide-australia",
  "antibiotic-prescription-online-australia",
  "antibiotics-when-appropriate",
  "are-antibiotics-prescription-only-australia",
  "are-online-medical-certificates-valid-australia",
  "asthma-treatment-online-australia",
  "medical-certificate-mental-health-day",
  "eczema-dermatitis",
  "telehealth-after-hours",
  "medical-certificate-food-poisoning",
  "sinusitis",
  "hay-fever-allergies",
  "medical-certificate-period-pain",
  "university-medical-certificates",
  "vertigo-dizziness",
  "medical-certificate-centrelink",
  "gout",
  "medical-certificate-surgery-recovery",
  "pbs-pharmaceutical-benefits-scheme",
  "medical-certificate-pregnancy-related-absence",
] as const

export type TopVisualArticleSlug = (typeof TOP_VISUAL_ARTICLE_SLUGS)[number]

export interface ArticleVisualItem {
  label: string
  detail: string
  tone?: "neutral" | "safe" | "caution" | "urgent"
}

export interface ArticleVisual {
  id: string
  title: string
  eyebrow: string
  summary: string
  kind: "comparison" | "flow" | "timeline" | "warning" | "checklist" | "spectrum"
  accent: "blue" | "emerald" | "amber" | "rose" | "sky"
  items: ArticleVisualItem[]
  imagePrompt: string
  assetPath?: string
}

const visualLibrary: Record<TopVisualArticleSlug, ArticleVisual[]> = {
  "ibs-digestive-issues": [
    {
      id: "ibs-subtype-map",
      eyebrow: "Subtype map",
      title: "IBS patterns change the management conversation",
      summary: "The same diagnosis can present as constipation, diarrhoea, mixed bowel habits, or an unclassified pattern.",
      kind: "comparison",
      accent: "blue",
      items: [
        { label: "IBS-C", detail: "Hard or infrequent stools predominate" },
        { label: "IBS-D", detail: "Loose, urgent, or frequent stools predominate" },
        { label: "IBS-M", detail: "Hard and loose stools occur in the same week" },
        { label: "IBS-U", detail: "Symptoms do not fit the main patterns" },
      ],
      imagePrompt: "Australian editorial health infographic, abstract gut-brain and bowel pattern mapping, calm warm ivory background, no readable text, no anatomy gore, premium clinical style",
      assetPath: "/images/blog/ibs-digestive-issues/ibs-subtype-map.webp",
    },
    {
      id: "fodmap-three-phase",
      eyebrow: "Diet pathway",
      title: "Low FODMAP is a three-phase process",
      summary: "The goal is not permanent restriction. The useful endpoint is a personalised diet that identifies specific triggers.",
      kind: "flow",
      accent: "emerald",
      items: [
        { label: "Elimination", detail: "Short trial to see whether FODMAPs matter" },
        { label: "Reintroduction", detail: "Test categories one at a time" },
        { label: "Personalisation", detail: "Keep variety while avoiding proven triggers" },
      ],
      imagePrompt: "Calm Australian kitchen health visual with food diary, phone, tea, and fresh low FODMAP ingredients, no readable labels, warm daylight, premium editorial photo style",
      assetPath: "/images/blog/ibs-digestive-issues/fodmap-three-phase.webp",
    },
    {
      id: "ibs-red-flags",
      eyebrow: "Safety boundary",
      title: "Symptoms that do not fit simple IBS",
      summary: "Blood, weight loss, night symptoms, fever, anaemia, and new symptoms after 50 need investigation before assuming IBS.",
      kind: "warning",
      accent: "rose",
      items: [
        { label: "Blood or anaemia", detail: "Needs investigation", tone: "urgent" },
        { label: "Unintentional weight loss", detail: "Do not treat as routine IBS", tone: "urgent" },
        { label: "Symptoms waking you", detail: "More concerning than daytime-only symptoms", tone: "caution" },
      ],
      imagePrompt: "Minimal medical warning still-life for digestive red flags, no people, no clinicians, no faces, calm red accent, abstract checklist shapes, phone and paper note only, no readable text, no graphic body imagery",
      assetPath: "/images/blog/ibs-digestive-issues/ibs-red-flags.webp",
    },
  ],
  "conjunctivitis-pink-eye": [
    {
      id: "conjunctivitis-type-map",
      eyebrow: "Type map",
      title: "Viral, bacterial, and allergic conjunctivitis look different",
      summary: "Discharge, itch, laterality, and contagiousness help separate the common patterns.",
      kind: "comparison",
      accent: "blue",
      items: [
        { label: "Viral", detail: "Watery, gritty, often follows a cold" },
        { label: "Bacterial", detail: "Thick discharge and sticky eyelids" },
        { label: "Allergic", detail: "Intense itch and both eyes at once" },
      ],
      imagePrompt: "Clean textless red eye comparison infographic base, three abstract eye symptom panels with distinct watery, sticky, and allergy motifs, warm ivory background, restrained blue and amber accents, no readable text, no labels, no graphic medical imagery, no faces",
    },
    {
      id: "red-eye-urgent-signs",
      eyebrow: "Urgent signs",
      title: "Some red-eye symptoms need same-day assessment",
      summary: "Pain, vision change, light sensitivity, corneal haze, injury, or newborn eye discharge are not routine conjunctivitis.",
      kind: "warning",
      accent: "rose",
      items: [
        { label: "Pain or vision change", detail: "Do not manage as routine pink eye", tone: "urgent" },
        { label: "Light sensitivity", detail: "Needs prompt assessment", tone: "urgent" },
        { label: "Contact lens use", detail: "Higher risk of corneal infection", tone: "caution" },
      ],
      imagePrompt: "Minimal textless red-eye warning still life, blank phone screen, soft rose warning shape, abstract eye outline, warm clinical palette, no readable text, no injury detail, no clinician, no face",
    },
    {
      id: "contact-lens-boundary",
      eyebrow: "Contact lenses",
      title: "Contact lens wearers need a stricter safety boundary",
      summary: "Stop lenses immediately and get assessed before restarting if symptoms, pain, or light sensitivity are present.",
      kind: "checklist",
      accent: "amber",
      items: [
        { label: "Stop lenses", detail: "Switch to glasses while symptomatic", tone: "caution" },
        { label: "Discard exposed disposables", detail: "Avoid reintroducing contamination" },
        { label: "Assess before restarting", detail: "Especially after pain or blurred vision", tone: "urgent" },
      ],
      imagePrompt: "Textless contact lens safety visual, lens case, glasses, clean sink counter, warm morning light, subtle amber caution accents, no readable brand names, no faces, no medical procedure",
    },
  ],
  "medical-certificate-carers-leave": [
    {
      id: "carers-leave-evidence-options",
      eyebrow: "Evidence options",
      title: "Carer's leave evidence does not always mean one document",
      summary: "A medical certificate or statutory declaration can support the leave, depending on what was reasonably practicable.",
      kind: "comparison",
      accent: "blue",
      items: [
        { label: "Medical certificate", detail: "For the person who was ill or injured" },
        { label: "Statutory declaration", detail: "Useful when a certificate was not practical" },
        { label: "Work policy", detail: "Awards and agreements may add process details" },
      ],
      imagePrompt: "Textless Australian carers leave evidence still life, blank certificate shape, blank statutory declaration page, phone, warm ivory desk, restrained blue accents, no readable text, no employer logos, no fake forms",
    },
    {
      id: "certificate-for-patient",
      eyebrow: "Certificate boundary",
      title: "The certificate is about the person needing care",
      summary: "The document should confirm the cared-for person's condition and dates, not disclose unnecessary family details.",
      kind: "checklist",
      accent: "emerald",
      items: [
        { label: "Patient name", detail: "The unwell family or household member" },
        { label: "Capacity need", detail: "Care or support was required" },
        { label: "Dates", detail: "The period the certificate covers" },
      ],
      imagePrompt: "Textless caring support evidence still life, warm home table, blank document, water glass, soft blanket, medicine cup with no label, no people, no hands, no faces, no readable text, no hospital setting, calm Australian morning light",
    },
    {
      id: "emergency-carers-leave",
      eyebrow: "Unexpected events",
      title: "Emergency carer's leave is for separate unexpected occasions",
      summary: "Unexpected illness or injury can trigger unpaid leave even when paid personal leave is exhausted.",
      kind: "timeline",
      accent: "amber",
      items: [
        { label: "Unexpected need", detail: "A family or household member requires care" },
        { label: "Notify employer", detail: "As soon as practicable" },
        { label: "Provide evidence if asked", detail: "Reasonable evidence may be requested" },
      ],
      imagePrompt: "Textless emergency carers leave timeline concept, blank calendar, phone with blank screen, home care items, warm ivory and amber accents, no readable text, no dramatic emergency imagery",
    },
  ],
  shingles: [
    {
      id: "shingles-treatment-window",
      eyebrow: "Timing",
      title: "The antiviral window is measured from rash onset",
      summary: "Assessment is most useful early because antiviral benefit falls as the rash progresses.",
      kind: "timeline",
      accent: "rose",
      items: [
        { label: "First symptoms", detail: "Burning, tingling, or sensitivity can start before rash" },
        { label: "Rash appears", detail: "Same-day assessment is the safest target", tone: "caution" },
        { label: "Around 72 hours", detail: "Benefit can decline for uncomplicated cases", tone: "urgent" },
      ],
      imagePrompt: "Textless shingles treatment timing visual, blank calendar, phone with blank screen, soft rose timing arc, no pills, no medicine brands, no readable text, no people, no graphic rash, warm ivory clinical background",
    },
    {
      id: "shingles-urgent-locations",
      eyebrow: "Urgent locations",
      title: "Face, eye, ear, and immune-risk shingles need faster care",
      summary: "Eye symptoms, forehead rash, ear pain, facial weakness, pregnancy, or immunosuppression change the urgency.",
      kind: "warning",
      accent: "rose",
      items: [
        { label: "Eye or forehead", detail: "Needs urgent assessment", tone: "urgent" },
        { label: "Ear or facial weakness", detail: "Do not manage as routine shingles", tone: "urgent" },
        { label: "Immune risk", detail: "In-person or urgent care may be needed", tone: "caution" },
      ],
      imagePrompt: "Minimal textless shingles urgent-location safety illustration, abstract head outline with eye and ear zones shown as simple shapes, warm ivory background, restrained rose accents, no readable text, no rash detail, no faces, no clinicians",
    },
    {
      id: "shingles-contagion-boundary",
      eyebrow: "Spread boundary",
      title: "Cover blisters until they crust",
      summary: "Shingles is spread through blister fluid to people who are not immune to chickenpox, not by casual proximity alone.",
      kind: "checklist",
      accent: "amber",
      items: [
        { label: "Cover rash", detail: "Reduce direct contact with blister fluid" },
        { label: "Avoid vulnerable people", detail: "Infants, pregnant people, and immunocompromised contacts", tone: "caution" },
        { label: "Wait for crusting", detail: "Transmission risk falls once blisters have crusted" },
      ],
      imagePrompt: "Textless shingles contagion boundary still life, folded clothing, covered bandage packet with no text, clean towel, warm morning light, amber caution accent, no skin close-up, no rash, no readable text, no people",
    },
  ],
  "acid-reflux-gerd": [
    {
      id: "reflux-mechanism",
      eyebrow: "Mechanism",
      title: "Reflux starts at the barrier between stomach and oesophagus",
      summary: "When the lower oesophageal sphincter relaxes too easily, acid can move upward and irritate tissue not built for stomach acid.",
      kind: "flow",
      accent: "amber",
      items: [
        { label: "Stomach pressure", detail: "Large meals, lying flat, pregnancy, or weight gain can increase pressure" },
        { label: "Barrier weakness", detail: "The sphincter does not fully protect the oesophagus" },
        { label: "Irritation", detail: "Repeated exposure can cause symptoms and inflammation" },
      ],
      imagePrompt: "Textless acid reflux mechanism illustration, abstract oesophagus and stomach barrier shown as simple warm shapes, no labels, no readable text, no gore, no body close-up, premium Australian health editorial style, warm ivory background",
    },
    {
      id: "reflux-red-flags",
      eyebrow: "Red flags",
      title: "Some symptoms should not be assumed to be reflux",
      summary: "Chest pain, swallowing difficulty, bleeding signs, weight loss, persistent vomiting, or new symptoms later in life need prompt assessment.",
      kind: "warning",
      accent: "rose",
      items: [
        { label: "Chest pain", detail: "Call 000 if cardiac symptoms are possible", tone: "urgent" },
        { label: "Swallowing trouble", detail: "Food sticking or painful swallowing needs review", tone: "urgent" },
        { label: "Bleeding or weight loss", detail: "Black stools, vomiting blood, or unexplained weight loss are not routine reflux", tone: "urgent" },
      ],
      imagePrompt: "Minimal textless reflux red-flag safety still life, blank phone screen, abstract chest warning shape, soft rose accent, warm clinical palette, no readable text, no people, no distressing imagery",
    },
    {
      id: "reflux-treatment-steps",
      eyebrow: "Treatment pathway",
      title: "Good reflux care steps up and steps down",
      summary: "Lifestyle changes, short medication trials, review, and step-down planning prevent indefinite treatment without reassessment.",
      kind: "timeline",
      accent: "emerald",
      items: [
        { label: "Lifestyle baseline", detail: "Meals, timing, sleep position, weight, smoking, and triggers" },
        { label: "Short treatment trial", detail: "Antacids, H2 blockers, or PPIs may be appropriate" },
        { label: "Review and step down", detail: "Use the lowest effective approach once symptoms settle" },
      ],
      imagePrompt: "Textless reflux treatment pathway still life, blank food diary, water glass, neutral medicine box with no letters, wedge pillow silhouette, warm morning light, emerald accent, no readable text, no brand names, no people",
    },
  ],
  "ahpra-registered-doctor-meaning": [
    {
      id: "ahpra-register-check",
      eyebrow: "Verification",
      title: "The public register is the source of truth",
      summary: "A real check confirms the practitioner, profession, registration status, type, conditions, and renewal details.",
      kind: "checklist",
      accent: "blue",
      items: [
        { label: "Name and profession", detail: "Make sure the result is the right person and profession" },
        { label: "Registration status", detail: "Current status matters more than a logo claim" },
        { label: "Conditions", detail: "Public restrictions or supervision requirements may appear" },
      ],
      imagePrompt: "Textless Australian health practitioner register verification still life, blank laptop screen, blank ID-style card, soft blue checkmark shapes, warm ivory desk, no readable text, no logos, no names, no people, premium editorial style",
    },
    {
      id: "medical-registration-types",
      eyebrow: "Registration types",
      title: "Registration type explains the scope of practice",
      summary: "General, specialist, provisional, limited, and non-practising registration do not mean the same thing.",
      kind: "comparison",
      accent: "emerald",
      items: [
        { label: "General or specialist", detail: "Usually permits independent practice within scope" },
        { label: "Provisional or limited", detail: "Often includes supervision or specific limits", tone: "caution" },
        { label: "Non-practising", detail: "Does not permit clinical practice", tone: "urgent" },
      ],
      imagePrompt: "Textless medical registration type comparison visual, organised blank credential cards in distinct groups on a clean desk, restrained emerald and blue accents, no readable text, no official logos, no people, no faces, no clinicians, no human silhouettes, no shadows resembling people",
    },
    {
      id: "telehealth-accountability",
      eyebrow: "Accountability",
      title: "Telehealth does not lower the professional standard",
      summary: "The Medical Board's expectations still apply: adequate assessment, clinical judgement, records, privacy, and follow-up where needed.",
      kind: "flow",
      accent: "amber",
      items: [
        { label: "Assess", detail: "Gather enough history and context" },
        { label: "Decide", detail: "Exercise clinical judgement for the individual patient" },
        { label: "Document", detail: "Keep records and arrange follow-up where appropriate" },
      ],
      imagePrompt: "Textless telehealth accountability workflow still life, blank phone, blank notes, abstract clinical decision nodes, warm ivory background, amber accents, no readable text, no people, no doctors, no brand marks",
    },
  ],
  "amoxicillin-guide-australia": [
    {
      id: "antibiotic-fit-check",
      eyebrow: "Fit check",
      title: "Amoxicillin only helps when the target is bacterial",
      summary: "Colds, flu, COVID, most coughs, and many sore throats are viral, so antibiotics do not treat the cause.",
      kind: "comparison",
      accent: "blue",
      items: [
        { label: "Bacterial pattern", detail: "May need antibiotics when clinically indicated" },
        { label: "Viral pattern", detail: "Antibiotics add risk without benefit", tone: "caution" },
        { label: "Unclear pattern", detail: "Assessment matters before prescribing", tone: "caution" },
      ],
      imagePrompt: "Textless antibiotic fit-check infographic base, abstract bacteria and virus shapes separated into two simple panels, blank medicine box, warm ivory background, restrained blue and amber accents, no readable text, no brand names, no pills spilling, no people",
    },
    {
      id: "penicillin-allergy-boundary",
      eyebrow: "Allergy boundary",
      title: "A penicillin allergy label needs careful history",
      summary: "A childhood rash is different from hives, throat swelling, breathing trouble, or anaphylaxis.",
      kind: "warning",
      accent: "rose",
      items: [
        { label: "Anaphylaxis symptoms", detail: "Breathing trouble or swelling is urgent", tone: "urgent" },
        { label: "Rash history", detail: "Timing and features matter", tone: "caution" },
        { label: "Delabelling", detail: "Formal assessment may clarify uncertain labels" },
      ],
      imagePrompt: "Minimal textless penicillin allergy safety still life, blank allergy card, soft rose warning shape, neutral medicine box with no letters, warm clinical desk, no readable text, no brand names, no people, no hives or graphic skin",
    },
    {
      id: "antibiotic-stewardship",
      eyebrow: "Stewardship",
      title: "The narrowest effective antibiotic protects future treatment",
      summary: "Antibiotic stewardship means using the right drug, for the right infection, at the right dose and duration.",
      kind: "flow",
      accent: "emerald",
      items: [
        { label: "Confirm need", detail: "Is an antibiotic likely to help?" },
        { label: "Choose narrow", detail: "Avoid broader cover when plain amoxicillin is enough" },
        { label: "Review response", detail: "Escalate only when the clinical picture warrants it" },
      ],
      imagePrompt: "Textless antibiotic stewardship pathway still life, blank guideline sheet, neutral medicine box, clean green shield shape, warm ivory background, no readable text, no official logos, no people, no pharmacy branding",
    },
  ],
  "antibiotic-prescription-online-australia": [
    {
      id: "telehealth-antibiotic-fit",
      eyebrow: "Telehealth fit",
      title: "Remote antibiotic prescribing needs a clear clinical pattern",
      summary: "A structured history can be enough for some low-risk infections, but uncertainty or severity changes the pathway.",
      kind: "comparison",
      accent: "blue",
      items: [
        { label: "Good fit", detail: "Clear, low-risk symptoms with no red flags", tone: "safe" },
        { label: "Needs examination", detail: "Ear, eye, deep skin, children, pregnancy, or unclear diagnosis", tone: "caution" },
        { label: "Emergency", detail: "Sepsis signs, severe pain, or rapidly spreading infection", tone: "urgent" },
      ],
      imagePrompt: "Textless telehealth antibiotic suitability visual, blank phone, abstract decision split, neutral medicine box, warm ivory background, blue and rose accents, no readable text, no brand names, no people, no pills spilling",
    },
    {
      id: "antibiotic-red-flags",
      eyebrow: "Safety boundary",
      title: "Some infection symptoms should bypass telehealth",
      summary: "Fever with systemic illness, confusion, rapid spread, severe pain, pregnancy, immune risk, or children usually need in-person assessment.",
      kind: "warning",
      accent: "rose",
      items: [
        { label: "Sepsis signs", detail: "Confusion, rigors, faintness, rapid heart rate", tone: "urgent" },
        { label: "Rapid spread", detail: "Redness or swelling expanding quickly", tone: "urgent" },
        { label: "Higher-risk patient", detail: "Pregnancy, child, diabetes, immunosuppression", tone: "caution" },
      ],
      imagePrompt: "Minimal textless infection red-flag safety still life, blank phone screen, soft rose warning triangle, thermometer shape without numbers, warm clinical surface, no readable text, no people, no graphic wounds, no gore",
    },
    {
      id: "escript-pharmacy-pathway",
      eyebrow: "Prescription pathway",
      title: "An eScript is only the dispensing step",
      summary: "The clinical decision comes first; the pharmacy token only matters after an antibiotic is judged appropriate.",
      kind: "flow",
      accent: "emerald",
      items: [
        { label: "Assess need", detail: "Bacterial likelihood and safety risks" },
        { label: "Choose medicine", detail: "Guideline, allergy, pregnancy, and resistance factors" },
        { label: "Dispense safely", detail: "Pharmacist checks and counselling still apply" },
      ],
      imagePrompt: "Textless eScript and pharmacy pathway still life, blank phone token shape, neutral medicine box, small green check shape, no pharmacy logos, no readable text, no people, warm ivory desk",
    },
  ],
  "antibiotics-when-appropriate": [
    {
      id: "bacterial-vs-viral",
      eyebrow: "Core distinction",
      title: "Antibiotics treat bacteria, not viruses",
      summary: "The decision starts with the likely cause of infection, not how miserable the symptoms feel.",
      kind: "comparison",
      accent: "blue",
      items: [
        { label: "Bacterial", detail: "May benefit from targeted antibiotics when clinically supported" },
        { label: "Viral", detail: "Colds, flu, COVID, and most coughs do not respond", tone: "caution" },
        { label: "Mixed uncertainty", detail: "Duration, severity, tests, and exam may matter" },
      ],
      imagePrompt: "Textless bacterial versus viral infection comparison, two abstract panels, bacteria shown as simple rounded rods and dots, viruses shown as generic respiratory virus spheres with small surface spikes, no bacteriophage leg shapes, warm ivory background, restrained blue and amber accents, no readable text, no medicine brands, no people, no scary germs",
    },
    {
      id: "watchful-waiting-window",
      eyebrow: "Timing",
      title: "Many respiratory infections improve without antibiotics",
      summary: "Duration, worsening pattern, fever, breathing symptoms, and risk factors matter more than mucus colour alone.",
      kind: "timeline",
      accent: "amber",
      items: [
        { label: "Early days", detail: "Viral infections commonly peak and then settle" },
        { label: "Persisting", detail: "Symptoms beyond expected course may need review", tone: "caution" },
        { label: "Red flags", detail: "Breathing trouble, severe pain, confusion, or dehydration need prompt care", tone: "urgent" },
      ],
      imagePrompt: "Textless respiratory infection watchful-waiting timeline still life, blank calendar, tissue box with no logo, thermometer without numbers, warm morning light, amber accents, no readable text, no people",
    },
    {
      id: "resistance-selection-pressure",
      eyebrow: "Resistance",
      title: "Unnecessary antibiotics create selection pressure",
      summary: "Every avoidable course gives bacteria more chances to adapt, spread, and make future infections harder to treat.",
      kind: "flow",
      accent: "emerald",
      items: [
        { label: "Use only when needed", detail: "Right indication first" },
        { label: "Use the right option", detail: "Narrow and guideline-aligned when possible" },
        { label: "Use as directed", detail: "Dose and duration matter" },
      ],
      imagePrompt: "Textless antimicrobial resistance selection pressure concept, abstract bacteria shapes near shield and guideline page, warm ivory background, emerald accent, no readable text, no pills spilling, no people, clean editorial health style",
    },
  ],
  "are-antibiotics-prescription-only-australia": [
    {
      id: "schedule-four-gate",
      eyebrow: "Schedule 4",
      title: "Systemic antibiotics sit behind a prescribing checkpoint",
      summary: "Prescription-only status exists because diagnosis, allergy risk, interactions, and resistance all matter.",
      kind: "checklist",
      accent: "blue",
      items: [
        { label: "Authorised prescriber", detail: "A clinician must assess whether treatment is appropriate" },
        { label: "Pharmacy dispensing", detail: "The prescription is checked before supply" },
        { label: "No self-supply", detail: "Leftovers and offshore sellers bypass safety checks", tone: "urgent" },
      ],
      imagePrompt: "Textless Schedule 4 prescription checkpoint still life, blank prescription document, neutral medicine box, blue gate or checkpoint shape, warm ivory desk, no readable text, no official logos, no brand names, no people",
    },
    {
      id: "why-prescription-only",
      eyebrow: "Why controlled",
      title: "The rule protects diagnosis, safety, and antibiotic effectiveness",
      summary: "The same symptom can be viral, bacterial, allergic, inflammatory, or urgent, so the medicine cannot be treated like a commodity.",
      kind: "comparison",
      accent: "emerald",
      items: [
        { label: "Correct diagnosis", detail: "Antibiotics do not treat viral illness" },
        { label: "Safety checks", detail: "Allergy, pregnancy, kidney function, and interactions" },
        { label: "Resistance control", detail: "Avoidable use makes future infections harder to treat" },
      ],
      imagePrompt: "Textless antibiotic prescription-only rationale visual, three clean abstract panels for diagnosis, safety, and resistance, warm ivory background, emerald and amber accents, no readable text, no people, no official marks",
    },
    {
      id: "unsafe-antibiotic-sources",
      eyebrow: "Unsafe sources",
      title: "Leftovers and offshore sellers remove the clinical safety layer",
      summary: "Old, partial, counterfeit, degraded, or mismatched antibiotics can delay the right care and increase harm.",
      kind: "warning",
      accent: "rose",
      items: [
        { label: "Leftover course", detail: "Wrong drug or incomplete duration", tone: "caution" },
        { label: "Offshore seller", detail: "Counterfeit or poorly stored medicine risk", tone: "urgent" },
        { label: "Wrong diagnosis", detail: "Symptoms may need urgent assessment", tone: "urgent" },
      ],
      imagePrompt: "Minimal textless unsafe antibiotic source warning still life, closed unlabelled medicine box, blank warning card, soft rose caution shape, warm clinical desk, no readable text, no pills, no people, no website screens",
    },
  ],
  "are-online-medical-certificates-valid-australia": [
    {
      id: "certificate-validity-checklist",
      eyebrow: "Validity checklist",
      title: "A certificate depends on issuer, assessment, dates, and clarity",
      summary: "The useful question is not paper versus online; it is whether the evidence would satisfy a reasonable person.",
      kind: "checklist",
      accent: "blue",
      items: [
        { label: "Registered practitioner", detail: "Identifiable AHPRA-registered clinician" },
        { label: "Clinical assessment", detail: "A genuine fitness-for-work judgement" },
        { label: "Clear dates", detail: "Consultation date and incapacity period" },
      ],
      imagePrompt: "Textless medical certificate validity checklist still life, blank certificate document, blank verification card, soft blue check shapes, warm ivory desk, no readable text, no logos, no names, no people",
    },
    {
      id: "reasonable-evidence-standard",
      eyebrow: "Fair Work standard",
      title: "Fair Work focuses on reasonable evidence",
      summary: "A valid telehealth certificate should not be rejected simply because it was online, but employers can ask reasonable evidence questions.",
      kind: "comparison",
      accent: "emerald",
      items: [
        { label: "Usually acceptable", detail: "Registered practitioner and clear work-capacity dates", tone: "safe" },
        { label: "May raise questions", detail: "Missing details, inconsistent dates, or no assessment", tone: "caution" },
        { label: "Escalate calmly", detail: "Ask for the reason in writing and seek Fair Work advice" },
      ],
      imagePrompt: "Completely textless workplace sick-leave evidence balance visual, blank employer policy page with no letters or words, blank certificate with no title or words, balanced scale shapes, warm ivory background, emerald accent, no readable text, no logos, no people, no silhouettes, no hands",
    },
    {
      id: "telehealth-assessment-quality",
      eyebrow: "Assessment quality",
      title: "Telehealth validity still depends on clinical quality",
      summary: "A certificate issued after an adequate remote assessment is different from a document generated without real review.",
      kind: "warning",
      accent: "amber",
      items: [
        { label: "Adequate history", detail: "Symptoms, function, timing, and risk factors" },
        { label: "Clinician judgement", detail: "Fitness for work is assessed, not assumed" },
        { label: "Record keeping", detail: "The consultation should be documented" },
      ],
      imagePrompt: "Completely textless telehealth medical certificate quality visual, blank phone, blank notes, blank certificate with no title or words, warm ivory clinical desk, amber verification accent, no readable text, no letters, no faces, no doctors, no people, no hands, no brand marks",
    },
  ],
  "asthma-treatment-online-australia": [
    {
      id: "asthma-control-boundary",
      eyebrow: "Control check",
      title: "Asthma care starts with control, not just a refill",
      summary: "Reliever use, night symptoms, activity limits, and recent attacks show whether the current plan is still working.",
      kind: "checklist",
      accent: "blue",
      items: [
        { label: "Reliever frequency", detail: "Frequent use suggests poor control", tone: "caution" },
        { label: "Night waking", detail: "Symptoms overnight need review", tone: "caution" },
        { label: "Recent flare", detail: "Attack or oral steroid use changes the risk", tone: "urgent" },
      ],
      imagePrompt: "Completely textless asthma control checklist still life, blank asthma action plan with no title and no words, blank checklist boxes only, inhaler-shaped object with no brand text, phone with blank screen, warm ivory background, blue accents, no readable text, no letters, no logos, no people, no hands",
    },
    {
      id: "telehealth-asthma-boundary",
      eyebrow: "Telehealth boundary",
      title: "Stable asthma and worsening asthma need different pathways",
      summary: "Repeat medicine review can be remote for some established patients; diagnosis, deterioration, and children need in-person care.",
      kind: "comparison",
      accent: "emerald",
      items: [
        { label: "Stable established asthma", detail: "Medication review may be suitable remotely", tone: "safe" },
        { label: "Worsening control", detail: "Needs GP review and often examination", tone: "caution" },
        { label: "First diagnosis or child", detail: "Requires in-person assessment", tone: "urgent" },
      ],
      imagePrompt: "Textless asthma telehealth suitability visual, split path with blank phone on one side and blank clinic assessment card on the other, inhaler silhouette, warm clinical palette, emerald and amber accents, no readable text, no people, no medical logos",
    },
    {
      id: "asthma-emergency-signs",
      eyebrow: "Emergency signs",
      title: "Some asthma symptoms should bypass telehealth",
      summary: "Reliever not helping, trouble speaking, blue lips, exhaustion, or rapidly worsening breathing needs emergency care.",
      kind: "warning",
      accent: "rose",
      items: [
        { label: "Cannot speak normally", detail: "Emergency pathway", tone: "urgent" },
        { label: "Reliever not working", detail: "Follow asthma first aid and call 000", tone: "urgent" },
        { label: "Blue lips or exhaustion", detail: "Do not wait for online review", tone: "urgent" },
      ],
      imagePrompt: "Minimal textless asthma emergency warning visual, blank phone, soft rose warning triangle, inhaler silhouette, warm ivory clinical surface, no readable text, no people, no distressing patient imagery, no brand names",
    },
  ],
  "medical-certificate-mental-health-day": [
    {
      id: "mental-health-evidence-boundary",
      eyebrow: "Work evidence",
      title: "Mental health absence is still sick leave",
      summary: "The certificate should confirm fitness for work, not disclose private diagnosis details to an employer.",
      kind: "checklist",
      accent: "blue",
      items: [
        { label: "Fit or unfit for work", detail: "The work-capacity question is central" },
        { label: "Private diagnosis", detail: "Usually not required by an employer" },
        { label: "Review plan", detail: "Recurring episodes deserve proper follow-up" },
      ],
      imagePrompt: "Quiet Australian bedroom morning scene, phone and workplace leave form on laptop, calm mental health day mood, no readable text, no faces looking at camera",
    },
    {
      id: "support-escalation",
      eyebrow: "Escalation ladder",
      title: "When a bad day needs more support",
      summary: "Occasional stress leave and crisis symptoms are different problems and need different pathways.",
      kind: "timeline",
      accent: "rose",
      items: [
        { label: "Mild stress", detail: "Rest, document absence, monitor pattern", tone: "safe" },
        { label: "Recurring episodes", detail: "Arrange regular GP review", tone: "caution" },
        { label: "Self-harm thoughts", detail: "Use crisis support or call 000", tone: "urgent" },
      ],
      imagePrompt: "Abstract calm support ladder for mental wellbeing, warm ivory and soft blue, no readable text, no distressing imagery",
    },
  ],
  "eczema-dermatitis": [
    {
      id: "eczema-flare-cycle",
      eyebrow: "Flare cycle",
      title: "Dryness, itch, scratching, and inflammation reinforce each other",
      summary: "Good eczema care focuses on breaking the cycle and rebuilding the skin barrier.",
      kind: "flow",
      accent: "amber",
      items: [
        { label: "Dry barrier", detail: "Skin loses moisture and irritants enter" },
        { label: "Itch", detail: "Inflammation increases the urge to scratch" },
        { label: "Scratch damage", detail: "More barrier injury can restart the flare" },
      ],
      imagePrompt: "Clean non-graphic eczema skin barrier illustration, soft warm clinical colours, no readable text, no close-up wounds",
    },
    {
      id: "eczema-routine",
      eyebrow: "Care routine",
      title: "Barrier care is the daily baseline",
      summary: "Most plans combine trigger reduction, regular moisturiser, and short targeted treatment during flares.",
      kind: "checklist",
      accent: "emerald",
      items: [
        { label: "Moisturise often", detail: "Especially after washing" },
        { label: "Avoid irritants", detail: "Fragrance, harsh soaps, heat, and friction" },
        { label: "Treat flares early", detail: "Use clinician-directed treatment when needed" },
      ],
      imagePrompt: "Australian bathroom counter with moisturiser pump, soft towel, gentle skincare, warm morning light, no readable brand names",
    },
  ],
  "telehealth-after-hours": [
    {
      id: "after-hours-urgency-ladder",
      eyebrow: "Triage",
      title: "After-hours care starts with urgency",
      summary: "The right path depends on danger, severity, and whether a physical exam is needed.",
      kind: "timeline",
      accent: "rose",
      items: [
        { label: "Emergency", detail: "Chest pain, breathing trouble, stroke signs: call 000", tone: "urgent" },
        { label: "Same-day urgent", detail: "Severe or worsening symptoms need urgent care", tone: "caution" },
        { label: "Routine", detail: "Stable admin or mild symptoms may wait", tone: "safe" },
      ],
      imagePrompt: "Minimal after-hours healthcare triage ladder, phone on bedside table at night, calm not alarming, no readable text",
    },
    {
      id: "after-hours-fit",
      eyebrow: "Fit check",
      title: "Some problems are not solved by an online form",
      summary: "If diagnosis depends on examination, monitoring, imaging, or emergency treatment, telehealth is the wrong first stop.",
      kind: "comparison",
      accent: "blue",
      items: [
        { label: "Good fit", detail: "Stable, low-risk, information-based requests", tone: "safe" },
        { label: "Poor fit", detail: "Severe pain, injury, dehydration, or complex symptoms", tone: "caution" },
        { label: "Emergency", detail: "Time-critical symptoms should bypass telehealth", tone: "urgent" },
      ],
      imagePrompt: "Calm decision-tree concept for after-hours care, Australian phone and notepad, no readable labels, warm ivory background",
    },
  ],
  "medical-certificate-food-poisoning": [
    {
      id: "gastro-recovery-window",
      eyebrow: "Recovery window",
      title: "Food poisoning is usually short, but dehydration changes the risk",
      summary: "Most uncomplicated cases improve over one to three days. Worsening symptoms need review.",
      kind: "timeline",
      accent: "sky",
      items: [
        { label: "First 24 hours", detail: "Rest and fluids are the main focus" },
        { label: "1-3 days", detail: "Most uncomplicated cases settle" },
        { label: "Worsening", detail: "Fever, blood, severe pain, or dehydration needs care", tone: "urgent" },
      ],
      imagePrompt: "Australian kitchen bench with water glass, oral rehydration sachet, phone, calm illness recovery scene, no readable text",
    },
    {
      id: "food-handler-boundary",
      eyebrow: "Work safety",
      title: "Food handlers need a stricter return-to-work boundary",
      summary: "Work involving food service or vulnerable people may need longer exclusion after symptoms stop.",
      kind: "warning",
      accent: "amber",
      items: [
        { label: "Last diarrhoea or vomiting", detail: "Do not return while symptomatic", tone: "urgent" },
        { label: "Food handling", detail: "Often requires at least 48 hours symptom-free", tone: "caution" },
        { label: "Document the absence", detail: "Use evidence without oversharing details" },
      ],
      imagePrompt: "Subtle food service return-to-work safety illustration, apron and calendar, no readable text, warm clinical palette",
    },
  ],
  sinusitis: [
    {
      id: "sinusitis-timeline",
      eyebrow: "Timeline",
      title: "Most sinus symptoms start viral",
      summary: "Duration, worsening pattern, and severity matter more than pressure alone.",
      kind: "timeline",
      accent: "blue",
      items: [
        { label: "Days 1-7", detail: "Viral symptoms are common" },
        { label: "Persistent", detail: "Symptoms beyond 10 days may need review", tone: "caution" },
        { label: "Severe or worsening", detail: "Fever, swelling, or eye symptoms need prompt care", tone: "urgent" },
      ],
      imagePrompt: "Clean sinus pressure timeline illustration, tissue box and calendar, no readable text, soft Australian daylight",
    },
    {
      id: "sinusitis-red-flags",
      eyebrow: "Red flags",
      title: "Eye or neurological symptoms change the urgency",
      summary: "Swelling around the eye, vision changes, severe headache, confusion, or neck stiffness are not routine sinusitis.",
      kind: "warning",
      accent: "rose",
      items: [
        { label: "Eye swelling", detail: "Needs urgent assessment", tone: "urgent" },
        { label: "Vision change", detail: "Do not wait for routine care", tone: "urgent" },
        { label: "Severe headache", detail: "Especially with neck stiffness or confusion", tone: "urgent" },
      ],
      imagePrompt: "Minimal red-flag sinusitis safety illustration, abstract face outline, no readable text, no graphic symptoms",
    },
  ],
  "hay-fever-allergies": [
    {
      id: "nasal-spray-technique",
      eyebrow: "Technique",
      title: "Spray angle matters",
      summary: "Aiming slightly outward can improve effect and reduce irritation compared with spraying straight up the septum.",
      kind: "flow",
      accent: "emerald",
      items: [
        { label: "Gently clear nose", detail: "Do not over-irritate" },
        { label: "Aim outward", detail: "Point away from the nasal septum" },
        { label: "Use consistently", detail: "Steroid sprays often need regular use" },
      ],
      imagePrompt: "Clean hay fever nasal spray technique illustration, soft botanical background, no readable text",
    },
    {
      id: "hay-fever-control-stack",
      eyebrow: "Control stack",
      title: "Hay fever control is layered",
      summary: "Exposure reduction, correct spray use, and allergy medicines each solve a different part of the problem.",
      kind: "spectrum",
      accent: "sky",
      items: [
        { label: "Environment", detail: "Pollen, dust, pets, and mould" },
        { label: "Nose", detail: "Congestion and inflammation" },
        { label: "Eyes", detail: "Itch, watering, and irritation" },
      ],
      imagePrompt: "Textless Australian spring allergy still life, tissue box, closed window, soft pollen shapes outside, blank medicine packaging with no letters, no readable text, no people, calm daylight",
    },
  ],
  "medical-certificate-period-pain": [
    {
      id: "period-pain-patterns",
      eyebrow: "Pattern check",
      title: "Pain pattern determines whether it needs investigation",
      summary: "Severe, worsening, one-sided, or new pain deserves more than a routine certificate.",
      kind: "comparison",
      accent: "rose",
      items: [
        { label: "Common cramps", detail: "Predictable and similar to previous cycles" },
        { label: "Concerning pattern", detail: "Worsening, one-sided, new, or disabling", tone: "caution" },
        { label: "Urgent symptoms", detail: "Fever, fainting, pregnancy concern, or severe pain", tone: "urgent" },
      ],
      imagePrompt: "Calm period pain guide illustration, heat pack and calendar, warm respectful style, no readable text",
    },
    {
      id: "period-work-documentation",
      eyebrow: "Documentation",
      title: "The work note should focus on capacity",
      summary: "A certificate can support absence without disclosing private gynaecological details to an employer.",
      kind: "checklist",
      accent: "blue",
      items: [
        { label: "Unfit for work", detail: "State the relevant date or period" },
        { label: "Privacy", detail: "Diagnosis detail is usually not needed" },
        { label: "Follow-up", detail: "Recurring severe pain should be assessed" },
      ],
      imagePrompt: "Australian work-from-home sick day scene with calendar and heat pack, no readable text, calm privacy-focused mood",
    },
  ],
  "university-medical-certificates": [
    {
      id: "uni-document-checklist",
      eyebrow: "Evidence",
      title: "University documentation is about dates, impact, and timing",
      summary: "The useful certificate matches the affected class, exam, placement, or assessment window.",
      kind: "checklist",
      accent: "blue",
      items: [
        { label: "Relevant dates", detail: "Match the assessment or attendance period" },
        { label: "Functional impact", detail: "Explain why study was affected" },
        { label: "Institution rules", detail: "Check the submission deadline" },
      ],
      imagePrompt: "Textless Australian university desk still life, laptop with blank screen, blank calendar blocks, unlabelled folder, pen, no readable text or letters anywhere, no people, soft daylight",
    },
    {
      id: "uni-extension-timeline",
      eyebrow: "Timing",
      title: "Submit evidence before the admin window closes",
      summary: "Late documentation can be rejected even when the illness was real.",
      kind: "timeline",
      accent: "amber",
      items: [
        { label: "Illness day", detail: "Record symptoms and affected tasks" },
        { label: "Certificate", detail: "Get evidence that covers the relevant dates" },
        { label: "Submission", detail: "Upload before the university deadline", tone: "caution" },
      ],
      imagePrompt: "University special consideration timeline visual, laptop and planner, no readable text, warm ivory palette",
    },
  ],
  "vertigo-dizziness": [
    {
      id: "vertigo-patterns",
      eyebrow: "Pattern recognition",
      title: "Dizziness is not one symptom",
      summary: "Spinning, faintness, imbalance, and light-headedness point toward different causes and urgency.",
      kind: "comparison",
      accent: "sky",
      items: [
        { label: "Spinning", detail: "Often vestibular" },
        { label: "Faintness", detail: "Can be blood pressure, dehydration, or cardiac" },
        { label: "Neurological signs", detail: "Weakness, speech trouble, or new severe headache is urgent", tone: "urgent" },
      ],
      imagePrompt: "Clean dizziness pattern illustration with subtle circular motion lines, calm clinical style, no readable text",
    },
    {
      id: "dizziness-red-flags",
      eyebrow: "Urgency",
      title: "Stroke-like symptoms override routine vertigo care",
      summary: "Facial droop, arm weakness, speech trouble, severe headache, chest pain, or collapse needs urgent care.",
      kind: "warning",
      accent: "rose",
      items: [
        { label: "Face, arm, speech", detail: "Call 000", tone: "urgent" },
        { label: "Chest pain or collapse", detail: "Emergency pathway", tone: "urgent" },
        { label: "New severe headache", detail: "Prompt assessment", tone: "urgent" },
      ],
      imagePrompt: "Minimal textless emergency warning still life for dizziness, phone, abstract balance shapes, calm red accent, no readable text, no people, no body closeups, no distressing imagery",
    },
  ],
  "medical-certificate-centrelink": [
    {
      id: "centrelink-certificate-types",
      eyebrow: "Form fit",
      title: "Different Centrelink situations need different evidence",
      summary: "A short illness certificate is not the same as evidence for a long-term exemption or DSP application.",
      kind: "comparison",
      accent: "blue",
      items: [
        { label: "Short absence", detail: "Standard certificate may be enough" },
        { label: "Mutual obligations", detail: "Centrelink form requirements may apply" },
        { label: "DSP evidence", detail: "Usually needs treating history and reports", tone: "caution" },
      ],
      imagePrompt: "Australian admin paperwork scene, myGov-style laptop without readable screen text, folder and calendar, warm daylight",
    },
    {
      id: "centrelink-evidence-stack",
      eyebrow: "Evidence stack",
      title: "Long-term claims need more than a one-off note",
      summary: "Treating GP reports, specialist letters, investigations, and function history matter for complex claims.",
      kind: "checklist",
      accent: "amber",
      items: [
        { label: "Diagnosis", detail: "Clear and documented" },
        { label: "Treatment history", detail: "Shows what has been tried" },
        { label: "Functional impact", detail: "Connects condition to daily limits" },
      ],
      imagePrompt: "Textless organised evidence stack still life, blank folder, blank documents, calendar with no numbers or words, warm administrative healthcare style, no readable text, no people",
    },
  ],
  gout: [
    {
      id: "gout-flare-timeline",
      eyebrow: "Flare pattern",
      title: "Gout flares often peak fast",
      summary: "Sudden severe joint pain, swelling, warmth, and tenderness are typical, but infection can mimic it.",
      kind: "timeline",
      accent: "rose",
      items: [
        { label: "Sudden onset", detail: "Often overnight" },
        { label: "Peak pain", detail: "Can be intense in the first day" },
        { label: "Atypical features", detail: "Fever or spreading redness needs assessment", tone: "urgent" },
      ],
      imagePrompt: "Non-graphic gout flare concept, foot resting near bed with subtle red accent, no readable text, respectful clinical style",
    },
    {
      id: "gout-prevention-levers",
      eyebrow: "Prevention",
      title: "Long-term control is different from flare relief",
      summary: "Reducing future attacks usually means reviewing urate level, triggers, kidney function, and long-term plan.",
      kind: "checklist",
      accent: "emerald",
      items: [
        { label: "Urate target", detail: "Discuss blood testing and treatment goals" },
        { label: "Trigger pattern", detail: "Alcohol, dehydration, diet, illness, medicines" },
        { label: "Kidney and heart risk", detail: "Comorbidities change the plan" },
      ],
      imagePrompt: "Calm gout prevention visual, water glass, medication organiser without labels, healthy meal, no readable text",
    },
  ],
  "medical-certificate-surgery-recovery": [
    {
      id: "surgery-recovery-phases",
      eyebrow: "Recovery phases",
      title: "Recovery certificates should match the actual restriction",
      summary: "Pain, fatigue, wound care, driving, lifting, and infection risk can affect return-to-work timing.",
      kind: "timeline",
      accent: "blue",
      items: [
        { label: "Immediate recovery", detail: "Rest, pain control, wound care" },
        { label: "Functional return", detail: "Driving, lifting, standing, concentration" },
        { label: "Review", detail: "Complications or slow recovery need follow-up", tone: "caution" },
      ],
      imagePrompt: "Post-surgery home recovery scene, couch, water, discharge paperwork without readable text, calm warm daylight",
    },
    {
      id: "modified-duties",
      eyebrow: "Work capacity",
      title: "Return-to-work can be full, delayed, or modified",
      summary: "A useful plan distinguishes desk duties from physical duties and short shifts from full workload.",
      kind: "comparison",
      accent: "emerald",
      items: [
        { label: "Desk work", detail: "May return earlier if pain and fatigue allow" },
        { label: "Physical work", detail: "Lifting, bending, standing can need longer" },
        { label: "Red flags", detail: "Fever, wound changes, chest pain, or breathlessness", tone: "urgent" },
      ],
      imagePrompt: "Textless return-to-work planning still life after surgery, blank planner, blank calendar blocks, pen, water glass, calm clinical palette, no people, no doctors, no faces, no readable text",
    },
  ],
  "pbs-pharmaceutical-benefits-scheme": [
    {
      id: "pbs-price-pathway",
      eyebrow: "Cost pathway",
      title: "PBS cost depends on listing, eligibility, and safety net status",
      summary: "A medicine can be prescription-only without being subsidised for every patient or every indication.",
      kind: "flow",
      accent: "blue",
      items: [
        { label: "Listed medicine", detail: "Is it on the PBS?" },
        { label: "Patient criteria", detail: "Does the indication meet rules?" },
        { label: "Safety net", detail: "Costs may reduce after threshold" },
      ],
      imagePrompt: "Textless PBS medicine cost pathway still life, phone with blank screen, blank receipt shapes, neutral medicine box with no letters, no pharmacy signage, no Rx symbols, no people, calm daylight",
    },
    {
      id: "pbs-authority",
      eyebrow: "Authority rules",
      title: "Some PBS medicines need authority approval",
      summary: "Authority requirements are designed to match subsidy with clinical criteria.",
      kind: "checklist",
      accent: "amber",
      items: [
        { label: "Streamlined", detail: "Code may be used when criteria are met" },
        { label: "Authority required", detail: "Prescriber must confirm eligibility" },
        { label: "Private script", detail: "May cost more if PBS criteria are not met" },
      ],
      imagePrompt: "Textless authority approval checkpoint still life, blank forms, soft checkmark shapes, neutral medicine box with no letters, warm ivory and blue accents, no people, no clinicians, no readable text",
    },
  ],
  "medical-certificate-pregnancy-related-absence": [
    {
      id: "pregnancy-absence-reasons",
      eyebrow: "Common reasons",
      title: "Pregnancy-related absence can be legitimate sick leave",
      summary: "Nausea, fatigue, pain, bleeding concerns, appointments, and complications can affect work capacity.",
      kind: "spectrum",
      accent: "rose",
      items: [
        { label: "Common symptoms", detail: "Nausea, fatigue, pelvic pain" },
        { label: "Work demands", detail: "Standing, lifting, travel, long shifts" },
        { label: "Complications", detail: "Need clinician review and sometimes urgent care", tone: "caution" },
      ],
      imagePrompt: "Respectful pregnancy sick leave visual, calendar, water glass, soft blanket, no readable text, no medical examination imagery",
    },
    {
      id: "pregnancy-red-flags",
      eyebrow: "Urgent signs",
      title: "Some pregnancy symptoms should not wait",
      summary: "Bleeding, severe pain, fainting, severe headache, vision changes, reduced fetal movement, or breathlessness need prompt care.",
      kind: "warning",
      accent: "rose",
      items: [
        { label: "Bleeding or severe pain", detail: "Prompt medical assessment", tone: "urgent" },
        { label: "Headache or vision changes", detail: "Especially later in pregnancy", tone: "urgent" },
        { label: "Reduced fetal movement", detail: "Follow maternity service advice", tone: "urgent" },
      ],
      imagePrompt: "Minimal textless pregnancy red-flag safety still life, phone with blank screen, soft warning shape, blank notebook with no letters, calm serious tone, no people, no clinicians, no readable text",
    },
  ],
}

function withAssetPaths(slug: TopVisualArticleSlug, visuals: ArticleVisual[]): ArticleVisual[] {
  return visuals.map((visual) => ({
    ...visual,
    assetPath: visual.assetPath ?? `/images/blog/${slug}/${visual.id}.webp`,
  }))
}

export function getArticleVisuals(slug: string): ArticleVisual[] {
  const topSlug = slug as TopVisualArticleSlug
  const visuals = visualLibrary[topSlug]
  return visuals ? withAssetPaths(topSlug, visuals) : []
}

export function getAllTopArticleVisuals(): Record<TopVisualArticleSlug, ArticleVisual[]> {
  return Object.fromEntries(
    TOP_VISUAL_ARTICLE_SLUGS.map((slug) => [slug, withAssetPaths(slug, visualLibrary[slug])]),
  ) as Record<TopVisualArticleSlug, ArticleVisual[]>
}
