export { HealthArticleSchema } from "./article"
export { BreadcrumbSchema } from "./breadcrumb"
export { FAQSchema } from "./faq"
export { HowToSchema, MedCertHowToSchema, PrescriptionHowToSchema } from "./how-to"
export { MedicalBusinessSchema } from "./medical-business"
export { MedicalConditionSchema } from "./medical-condition"
export { MedicalServiceSchema } from "./medical-service"
export { OrganizationSchema } from "./organization"
export { ServiceSchema } from "./service"
export { SpeakableSchema } from "./speakable"
