// Marketing components barrel export
export { Hero } from './hero'
export { RotatingText } from './rotating-text'
export { HowItWorks } from './how-it-works'
export { MarketingFooter } from './footer'
export { LiveWaitTime } from './live-wait-time'
export { StatsStrip } from './total-patients-counter'
export { MediaMentions } from './media-mentions'
export { TrustBadgeSlider } from './trust-badge-slider'
export { PatientReviews } from './patient-reviews'
export { SampleCertificate } from './sample-certificate'
export { ServiceFunnelPage } from './service-funnel-page'
export { ServicePicker } from './service-picker'
