// Marketing components barrel export
export { Hero } from './hero'
export { RotatingText } from './rotating-text'
export { HowItWorks } from './how-it-works'
export { MarketingFooter } from './footer'
export { Stats } from '@/components/ui/statistics-card'
export { LiveWaitTime, ServiceWaitBadge } from './live-wait-time'
export { TotalPatientsCounter, StatsStrip } from './total-patients-counter'
export { MediaMentions } from './media-mentions'
export { TrustBadgeSlider } from './trust-badge-slider'
export { TrustBadges } from './trust-badges'
export { PatientReviews } from './patient-reviews'
export { SampleCertificate } from './sample-certificate'
export { ServiceFunnelPage } from './service-funnel-page'
export { ServicePicker } from './service-picker'
export { SectionDivider } from './section-divider'
