// Chat components exports
export { ChatIntake, ChatIntakeButton } from './chat-intake'
export { ChatIntakeButtonLazy } from './chat-intake-lazy'
export { ChatIntakeProvider, useChatIntakeContext } from './chat-intake-context'
export type { Message, QuickReply } from './chat-intake-context'
export { ChatHeader } from './chat-header'
export { ChatMessages } from './chat-messages'
export { ChatInputForm } from './chat-input-form'
export { ChatBubblePrompts } from './chat-bubble-prompts'
export { ChatRedirectOverlay } from './chat-redirect-overlay'
export { MessageBubble } from './message-bubble'
export { ChatTypingIndicator, InputTypingIndicator } from './typing-indicator'
export { ChatProgress, ChatProgressBar } from './chat-progress'
export { DoctorNotesPreview } from './doctor-notes-preview'
export { DraftResume } from './draft-resume'
export { MedicationSearchInline, isMedicationQuestion } from './medication-search-inline'
export { SmartDateSuggestions, SmartDurationSuggestions } from './smart-date-suggestions'
