import {
  existsSync,
  readdirSync,
  readFileSync,
} from "node:fs"
import { join } from "node:path"

import { describe, expect, it } from "vitest"

const root = process.cwd()
const read = (path: string) => readFileSync(join(root, path), "utf8")
const collectSourceFiles = (dir: string): string[] => {
  const absoluteDir = join(root, dir)
  const entries = readdirSync(absoluteDir, { withFileTypes: true })

  return entries.flatMap((entry) => {
    const relativePath = `${dir}/${entry.name}`

    if (entry.isDirectory()) return collectSourceFiles(relativePath)
    if (!/\.(ts|tsx)$/.test(entry.name)) return []

    return [relativePath]
  })
}

describe("dashboard simplicity and runtime performance contracts", () => {
  it("keeps the patient app shell free of decorative page-transition runtime", () => {
    const source = read("app/patient/patient-shell.tsx")

    expect(source).not.toContain("framer-motion")
    expect(source).not.toContain("AnimatePresence")
    expect(source).not.toContain("motion.div")
  })

  it("keeps the patient dashboard scannable without scroll-triggered animation wrappers", () => {
    const source = read("components/patient/panel-dashboard.tsx")

    expect(source).not.toContain("framer-motion")
    expect(source).not.toContain("whileInView")
    expect(source).not.toContain("stagger.")
    expect(source).toContain("next/dynamic")
    expect(source).toContain("profile-drawers")
    expect(source).toContain("patient/intake-detail-drawer")
    expect(source).toContain("patient/referral-card")
  })

  it("keeps patient routes off the broad patient component barrel", () => {
    expect(existsSync(join(root, "components/patient/index.ts"))).toBe(false)

    const patientRouteSources = [
      "app/patient/page.tsx",
      "app/patient/intakes/intakes-client.tsx",
      "app/patient/intakes/[id]/client.tsx",
      "app/patient/prescriptions/client.tsx",
      "app/patient/documents/documents-client.tsx",
      "app/patient/messages/messages-client.tsx",
    ]

    for (const file of patientRouteSources) {
      expect(read(file)).not.toContain('from "@/components/patient"')
    }
  })

  it("keeps profile housekeeping static and defers drawer forms until opened", () => {
    const todoSource = read("components/patient/profile-todo-card.tsx")
    const drawerSource = read("components/patient/profile-drawers.tsx")
    const panelDashboardSource = read("components/patient/panel-dashboard.tsx")

    expect(todoSource).not.toContain("framer-motion")
    expect(todoSource).not.toContain("AnimatePresence")
    expect(drawerSource).not.toContain("framer-motion")
    expect(drawerSource).toContain("@/components/panels/panel-provider")
    expect(panelDashboardSource).toContain("import(\"@/components/panels/drawer-panel\")")
  })

  it("keeps the default panel provider out of the Framer Motion bundle path", () => {
    const providerSource = read("components/panels/panel-provider.tsx")
    const patientShellSource = read("app/patient/patient-shell.tsx")

    expect(providerSource).not.toContain("framer-motion")
    expect(providerSource).not.toContain("AnimatePresence")
    expect(patientShellSource).toContain("@/components/panels/panel-provider")
    expect(patientShellSource).toContain("@/components/shell/left-rail")
    expect(patientShellSource).not.toContain("@/components/shell'")
    expect(existsSync(join(root, "components/shell/authenticated-shell.tsx"))).toBe(false)
  })

  it("avoids high-frequency whole-queue redraws in the staff cockpit", () => {
    const source = read("app/doctor/queue/queue-client.tsx")
    const queueUtilsSource = read("lib/doctor/queue-utils.ts")

    expect(source).toContain("getQueueClockTickDelayMs")
    expect(source).toContain("QUEUE_VISIBLE_WAIT_SECONDS_CADENCE")
    expect(source).toContain("window.setTimeout")
    expect(source).toContain("window.clearTimeout")
    expect(queueUtilsSource).toContain("return 1_000")
    expect(queueUtilsSource).toContain("afterFirstMinuteSecondsCadence")
    expect(queueUtilsSource).toContain("postMinuteCadenceMs")
    expect(queueUtilsSource).toContain("return Math.max(1_000, Math.min(postMinuteCadenceMs, nextBoundaryMs))")
    expect(source).toContain("if (intakes.length === 0)")
    expect(source).not.toContain("const freshQueueTickMs")
    expect(source).not.toContain("}, 30000)")
  })

  it("keeps staff queue DOM rows windowed at the scale boundary", () => {
    const source = read("app/doctor/queue/queue-table.tsx")

    expect(source).toContain("QUEUE_DOM_WINDOW_LIMIT = 100")
    expect(source).toContain("filteredIntakes.slice(0, QUEUE_DOM_WINDOW_LIMIT)")
    expect(source).toContain("renderedIntakes.map")
  })

  it("keeps queue hover from fetching full clinical review payloads", () => {
    expect(existsSync(join(root, "components/doctor/queue/queue-row-peek.tsx"))).toBe(false)
    expect(existsSync(join(root, "lib/doctor/review-data-cache.ts"))).toBe(false)

    const source = read("app/doctor/queue/queue-table.tsx")
    expect(source).not.toContain("prefetchReviewData")
    expect(source).not.toContain("onMouseEnter")
  })

  it("does not fetch or render unreachable dashboard earnings stats", () => {
    const dashboardPageSource = read("app/dashboard/page.tsx")
    const queueClientSource = read("app/doctor/queue/queue-client.tsx")
    const queueTypesSource = read("app/doctor/queue/types.ts")
    const intakeQueriesSource = read("lib/data/intakes/queries.ts")
    const intakeIndexSource = read("lib/data/intakes/index.ts")

    expect(dashboardPageSource).toContain("compactShell")
    expect(dashboardPageSource).not.toContain("getTodayEarnings")
    expect(dashboardPageSource).not.toContain("todayEarnings")
    expect(queueClientSource).not.toContain("todayEarnings")
    expect(queueClientSource).not.toContain("Daily stats strip")
    expect(queueClientSource).not.toContain("const approvalRate")
    expect(queueTypesSource).not.toContain("todayEarnings")
    expect(intakeQueriesSource).not.toContain("export async function getTodayEarnings")
    expect(intakeIndexSource).not.toContain("getTodayEarnings")
  })

  it("keeps the doctor queue header focused on current operational pressure", () => {
    const dashboardPageSource = read("app/dashboard/page.tsx")
    const queueClientSource = read("app/doctor/queue/queue-client.tsx")
    const queueFiltersSource = read("app/doctor/queue/queue-filters.tsx")
    const systemHealthSource = read("components/operator/system-health-pill.tsx")
    const queuePressureSource = read("components/operator/queue-pressure-signal.tsx")
    const queueTableSource = read("app/doctor/queue/queue-table.tsx")
    const userCardSource = read("components/uix/user-card.tsx")

    expect(dashboardPageSource).toContain("QueuePressureSignal")
    expect(dashboardPageSource).toContain("data-dashboard-wait-strip")
    expect(dashboardPageSource).toContain("showHeaderOperationalSummary")
    expect(dashboardPageSource).toContain("data-dashboard-median-tile")
    expect(dashboardPageSource).toContain("Median time to inbox")
    expect(queuePressureSource).toContain("Target: under 2h")
    expect(dashboardPageSource).not.toContain("prominent")
    expect(dashboardPageSource).toContain("oldestWaitingMinutes")
    expect(dashboardPageSource).toContain("oldestWaitingEnteredAt")
    expect(dashboardPageSource).toContain("showIcon={false}")
    expect(dashboardPageSource).not.toContain("softenWhenReviewOpen")
    expect(dashboardPageSource).toContain("jumpToOldestOnClick")
    expect(dashboardPageSource).toContain("getFormToInboxStats")
    expect(queueClientSource).toContain("oldestWaitingMinutes")
    expect(queueClientSource).not.toContain("Oldest wait")
    expect(queueClientSource).toContain("root.dataset.operatorReviewingCase")
    expect(queueClientSource).toContain("operator-reviewing-case-change")
    expect(queueClientSource).toContain("operator-jump-to-oldest-wait")
    expect(queueClientSource).toContain("handleJumpToOldestWait")
    expect(queueClientSource).not.toContain("QueueSummaryStrip")
    expect(queueClientSource).not.toContain("formToInboxStats")
    expect(queueClientSource).toContain("primeReviewPanelCode")
    expect(queueClientSource).not.toContain("QueueRunStatusStrip")
    expect(queueClientSource).toContain("showOldestWaiting={!compactShell}")
    expect(queueClientSource).not.toContain("queueContext={{")
    expect(queueClientSource).not.toContain("Next action")
    expect(queueClientSource).not.toContain("getNextCaseTriagePreview")
    expect(queueClientSource).not.toContain("Open the case to see ${nextPatientFirstName}'s details.")
    expect(queueClientSource).not.toContain("Queue flow")
    expect(queueClientSource).not.toContain("ChevronRight")
    expect(queueClientSource).not.toContain("Open ${nextPatientName || \"next\"} case")
    expect(queueClientSource).not.toContain(">Open case<")
    expect(queueClientSource).not.toContain("completed today.")
    expect(queueClientSource).toContain("Next up")
    expect(queueClientSource).not.toContain("No cases finished yet. First one's queued.")
    expect(queueClientSource).not.toContain("Next: ${nextPatientName")
    expect(queueClientSource).not.toContain("Single click the queue row.")
    expect(queueClientSource).not.toContain("Review oldest")
    expect(queueClientSource).toContain("const showNextUp = filteredCount > 0")
    expect(queueClientSource).toContain("{showNextUp ? (")
    expect(queueClientSource).not.toContain("visibleNextIntakes")
    expect(queueClientSource).toContain("nextIntakes={filteredIntakes.slice(0, 3)}")
    expect(queueClientSource).not.toContain("nextCaseButtonLabel")
    expect(queueClientSource).not.toContain("Target: oldest wait under 2h")
    expect(queueClientSource).not.toContain("grid grid-cols-3 gap-2")
    expect(queueClientSource).not.toContain(">Reviewed</p>")
    expect(queueClientSource).not.toContain("primaryMetricLabel")
    expect(queueClientSource).not.toContain("primaryMetricValue")
    expect(queueClientSource).not.toContain("Cases finished today")
    expect(queueClientSource).not.toContain("Target used")
    expect(queueClientSource).not.toContain("of the 2-hour target.")
    expect(queueClientSource).not.toContain("You're ${targetUsedPercent}% into the 2h target.")
    expect(queueClientSource).not.toContain("Right now")
    expect(queueClientSource).not.toContain("Next decision")
    expect(queueClientSource).not.toContain("Queue is clear.")
    expect(queueClientSource).not.toContain("is next.")
    expect(queueClientSource).not.toContain("Oldest visible case is ready.")
    expect(queueClientSource).not.toContain("No reviews completed today.")
    expect(queueClientSource).toContain("Showing older queue data. Refresh to see new arrivals.")
    expect(queueClientSource).toContain("getQueueClockTickDelayMs")
    expect(queueClientSource).toContain('role="status"')
    expect(queueClientSource).not.toContain("useRelativeRefreshAge")
    expect(queueClientSource).not.toContain("Updated this minute")
    expect(queuePressureSource).toContain("data-queue-pressure")
    expect(queuePressureSource).toContain("prominent?: boolean")
    expect(queuePressureSource).toContain("data-queue-pressure-softened")
    expect(queuePressureSource).toContain("softenWhenReviewOpen")
    expect(queuePressureSource).toContain("jumpToOldestOnClick")
    expect(queuePressureSource).toContain("operator-jump-to-oldest-wait")
    expect(queuePressureSource).toContain("operator-reviewing-case-change")
    expect(queuePressureSource).toContain("Target: under 2h")
    expect(queuePressureSource).toContain("to target")
    expect(queuePressureSource).toContain("waitingCaseCount")
    expect(queuePressureSource).toContain("data-live-wait-counter")
    expect(queuePressureSource).toContain("data-target-pressure-token")
    expect(queuePressureSource).toContain("getTargetTokenTone")
    expect(read("lib/doctor/queue-pressure.ts")).toContain("before target")
    expect(queuePressureSource).toContain("formatRefreshAge")
    expect(dashboardPageSource).toContain("waitingCaseCount={queueResult.total}")
    expect(read("lib/doctor/queue-pressure.ts")).toContain("No one waiting")
    expect(queueClientSource).not.toContain("Open it from the row")
    expect(queueClientSource).not.toContain("One case waiting -")
    expect(queueClientSource).not.toContain("liveMedianMinutes")
    expect(queueFiltersSource).toContain("Oldest wait")
    expect(queueFiltersSource).toContain("showOldestWaiting")
    expect(queueFiltersSource).toContain("getQueuePressureState")
    expect(queueFiltersSource).toContain("onOpenSingleMatch")
    expect(queueFiltersSource).toContain('event.key !== "Enter"')
    expect(queueFiltersSource).toContain("data-queue-pressure")
    expect(queueFiltersSource).toContain("Today's queue")
    expect(queueFiltersSource).toContain("matchLabel")
    expect(queueFiltersSource).not.toContain("formToInboxStats")
    expect(queueFiltersSource).not.toContain("Median form-to-inbox today")
    expect(queueFiltersSource).not.toContain("data-queue-breach-banner")
    expect(queueFiltersSource).toContain('aria-live="polite"')
    expect(queueTableSource).toContain("getPlainSearchHighlight")
    expect(queueTableSource).not.toContain("getCompactPatientDescription")
    expect(queueTableSource).toContain("compactShell")
    expect(queueClientSource).toContain("searchQuery={debouncedSearch}")
    expect(userCardSource).toContain("highlightQuery")
    expect(userCardSource).toContain("descriptionClassName")
    expect(userCardSource).toContain("<mark")
    expect(systemHealthSource).toContain("dominantSystemHealthLabel")
    expect(systemHealthSource).toContain("email failure")
    expect(queueFiltersSource).toContain("count === 0")
    expect(queueFiltersSource).not.toContain("Median wait")
    expect(queueFiltersSource).toContain("Open next case")
    expect(queueFiltersSource).toContain("filteredCount > 1")
    expect(queueFiltersSource).not.toContain("Case open")
    expect(queueFiltersSource).toContain("hasOpenCase")
    expect(queueFiltersSource).toContain("&& !hasOpenCase")
    expect(queueFiltersSource).not.toContain('variant={hasOpenCase ? "outline" : "default"}')
    expect(queueFiltersSource).not.toContain("border-border/70 bg-muted/30 text-muted-foreground")
    expect(queueFiltersSource).not.toContain("Finish or close the current case before opening the next one.")
    expect(queueFiltersSource).toContain("data-open-next-case")
    expect(queueFiltersSource).toContain("const showSearch = !compactShell || intakes.length > 5 || hasActiveSearch")
    expect(read("lib/doctor/queue-utils.ts")).toContain("getQueueClockTickDelayMs")
  })

  it("keeps the form-to-inbox metric real-only and med-cert scoped", () => {
    const queriesSource = read("lib/data/intakes/queries.ts")
    const queueClientSource = read("app/doctor/queue/queue-client.tsx")

    expect(queriesSource).toContain("getFormToInboxStats")
    expect(queriesSource).toContain("DEFAULT_FORM_TO_INBOX_MIN_SAMPLE_SIZE = 3")
    expect(queriesSource).toContain('service?.type === "med_certs"')
    expect(queriesSource).toContain('intake.category === "medical_certificate"')
    expect(queriesSource).not.toContain("14-minute")
    expect(read("app/dashboard/page.tsx")).toContain("formToInboxStats")
    expect(read("app/dashboard/page.tsx")).toContain("!onlyTestData")
    expect(read("app/dashboard/page.tsx")).toContain("Under 1m")
    expect(read("app/dashboard/page.tsx")).toContain("data-dashboard-median-tile")
    expect(queueClientSource).not.toContain("const primaryMetricDetail = formToInboxStats")
    expect(queueClientSource).not.toContain("Median form to inbox. Target under 2h.")
    expect(queueClientSource).not.toContain("Time from patient form to inbox today.")
    expect(queueClientSource).not.toContain('Last ${formToInboxStats.sampleSize} med certs issued.')
    expect(queueClientSource).not.toContain("Avg med cert today")
    expect(queueClientSource).not.toContain("Median form-to-inbox")
  })

  it("keeps split-view loading and row chrome calm under interaction", () => {
    const queueClientSource = read("app/doctor/queue/queue-client.tsx")
    const queueTableSource = read("app/doctor/queue/queue-table.tsx")
    const reviewPanelSource = read("components/doctor/intake-review-panel.tsx")
    const operatorPageSource = read("components/operator/operator-page.tsx")

    expect(queueClientSource).toContain("bg-[#F1EFEA]/80")
    expect(queueClientSource).toContain('mode={expandedId ? "reviewing" : "idle"}')
    expect(operatorPageSource).toContain('mode?: "idle" | "reviewing" | "dense"')
    expect(operatorPageSource).toContain("cubic-bezier(0.16,1,0.3,1)")
    expect(operatorPageSource).not.toContain("transition-[grid-template-columns]")
    expect(queueTableSource).toContain("min-w-fit whitespace-nowrap")
    expect(queueTableSource).toContain("showInlineWaitTime")
    expect(queueTableSource).toContain("showInlineWaitTime = true")
    expect(queueTableSource).toContain("displayWaitLabel")
    expect(queueTableSource).toContain('waitLabel === "just now" ? "Just arrived"')
    expect(queueTableSource).toContain("sm:grid-cols-[minmax(0,1fr)_auto]")
    expect(queueTableSource).toContain("before:bg-primary")
    expect(queueTableSource).toContain("before:w-1")
    expect(queueTableSource).toContain("bg-primary/[0.04]")
    expect(queueTableSource).toContain("bg-primary/[0.035]")
    expect(queueTableSource).toContain("shadow-[inset_3px_0_0_hsl(var(--primary))]")
    expect(queueTableSource).not.toContain("shadow-[inset_3px_0_0_hsl(var(--border))]")
    expect(queueTableSource).toContain("Selected")
    expect(queueTableSource).not.toContain("No one else waiting · target under 2h")
    expect(queueTableSource).toContain("onPointerEnter={onPrimeReviewPanelCode}")
    expect(queueClientSource).toContain("data-review-pane-entry")
    expect(queueClientSource).toContain("review-pane-in_280ms")
    expect(queueClientSource).toContain('data-testid="intake-review-loading"')
    expect(queueClientSource).toContain("data-review-skeleton-matched")
    expect(queueClientSource).toContain("data-review-skeleton-reserved")
    expect(queueClientSource).toContain("sm:grid-cols-4")
    expect(read("components/doctor/intake-review-panel.tsx")).toContain("review-pane-in_280ms")
    expect(read("app/globals.css")).toContain('html[data-operator-reviewing-case="true"] [data-dashboard-wait-strip]')
    expect(read("app/globals.css")).toContain("[data-dashboard-median-tile]")
    expect(read("app/globals.css")).toContain("transform: translateY(10px)")
    expect(queueClientSource).not.toContain("motion-safe:animate-[fade-in_150ms_ease-in-out]")
    expect(queueClientSource).not.toContain("fade-in-right_260ms")
    expect(queueTableSource).toContain("compactShell ? (")
    expect(queueTableSource).not.toContain("Follow-ups")
    expect(queueTableSource).not.toContain("No pending replies or scripts waiting")
    expect(queueTableSource).not.toContain("pendingReplyCount")
    expect(queueTableSource).not.toContain("scriptCount")
    expect(queueTableSource).not.toContain("getCompactNextActionLabel")
    expect(queueTableSource).not.toContain("prefetchReviewData")
    expect(queueTableSource).not.toContain("onMouseEnter")
    expect(reviewPanelSource).toContain("loadingAnswersLabel")
    expect(reviewPanelSource).toContain("Loading answers.")
    expect(reviewPanelSource).not.toContain("Buttons enable when answers load.")
    expect(reviewPanelSource).not.toContain("Approve and decline unlock")
    expect(reviewPanelSource).not.toContain('|| "Loading"')
    expect(reviewPanelSource).not.toContain("Pulling intake answers")
    expect(reviewPanelSource).not.toContain("clinical payload")
    expect(reviewPanelSource).not.toContain("Preparing review")
    expect(reviewPanelSource).toContain("Decision")
    expect(reviewPanelSource).toContain("Patient actions")
    expect(reviewPanelSource).toContain("formatCaseAnchorLine")
    expect(reviewPanelSource).toContain("data-case-anchor-line")
    expect(reviewPanelSource).toContain("First visit")
    expect(reviewPanelSource).toContain('inline ? "View profile" : "Patient profile"')
    expect(reviewPanelSource).toContain("Open full record")
    expect(reviewPanelSource).toContain("formatPreviewAgeDob")
    expect(reviewPanelSource).toContain("formatPreviewLocation")
    expect(reviewPanelSource).toContain("Review details took too long to load")
    expect(reviewPanelSource).toContain("Retry")
    expect(reviewPanelSource).not.toContain("InlineQueueContextStrip")
    expect(reviewPanelSource).not.toContain("QueueContextSummary")
    expect(reviewPanelSource).not.toContain("fade-in-right_200ms")
    expect(reviewPanelSource).toContain("fade-in-up_200ms")
    expect(reviewPanelSource).not.toContain("Opening {previewIntake.patient.full_name}")
    expect(reviewPanelSource).toContain("Checks")
    expect(reviewPanelSource).toContain("Draft note")
    expect(reviewPanelSource).toContain("data-review-skeleton-reserved")
    expect(reviewPanelSource).toContain("fallbackDraftNote")
    expect(reviewPanelSource).toContain("buildClinicalCaseSummary")
    expect(reviewPanelSource).not.toContain("notesRef.current?.focus({ preventScroll: true })")
    expect(reviewPanelSource).not.toContain("Intake answers")
    expect(reviewPanelSource).not.toContain("Prior scripts")
    expect(reviewPanelSource).toContain("bg-[#F1EFEA]/80")
    expect(reviewPanelSource).toContain("rounded-xl")
    expect(reviewPanelSource).not.toContain("bg-slate-200/70")
    expect(reviewPanelSource).not.toContain("Loading case details...")
  })

  it("keeps clinical action colours muted on the doctor surface", () => {
    const availabilityToggleSource = read("components/doctor/doctor-availability-toggle.tsx")
    const actionButtonsSource = read("components/doctor/review/intake-action-buttons.tsx")
    const intakePanelSource = read("components/doctor/intake-review-panel.tsx")
    const dashboardLayoutSource = read("app/dashboard/layout.tsx")

    expect(availabilityToggleSource).toContain("#7B8F80")
    expect(availabilityToggleSource).toContain("#637A68")
    expect(availabilityToggleSource).toContain('size={compact ? "sm" : "default"}')
    expect(actionButtonsSource).toContain("#2563EB")
    expect(actionButtonsSource).toContain("transition-colors")
    expect(actionButtonsSource).toContain("Cmd+Enter")
    expect(actionButtonsSource).toContain("Cmd+Shift+D")
    expect(actionButtonsSource).toContain("data-shortcut-hint")
    expect(actionButtonsSource).toContain("Decline with reason")
    expect(actionButtonsSource).toContain("data-decline-confirmation-copy")
    expect(actionButtonsSource).toContain("Full refund if you decline")
    expect(actionButtonsSource).toContain("sm:gap-x-6")
    expect(actionButtonsSource).not.toContain("refundConsequenceLabel")
    expect(actionButtonsSource).not.toContain("data-refund-consequence")
    expect(actionButtonsSource).not.toContain("gets ${refundShortLabel} back.")
    expect(actionButtonsSource).toContain("ActionReadinessChecks")
    expect(actionButtonsSource).toContain("data-action-readiness")
    expect(actionButtonsSource).toContain("data-action-readiness-summary")
    expect(actionButtonsSource).toContain("auditTrailLabel")
    expect(actionButtonsSource).toContain("DecisionWaitSignal")
    expect(actionButtonsSource).toContain("data-decision-wait-signal")
    expect(actionButtonsSource).toContain("QUEUE_WAIT_TARGET_MINUTES")
    expect(actionButtonsSource).toContain("getQueueClockTickDelayMs")
    expect(actionButtonsSource).toContain("DECISION_WAIT_SIGNAL_CADENCE_MS")
    expect(actionButtonsSource).toContain("to target")
    expect(actionButtonsSource).toContain("Certificate ready to send.")
    expect(actionButtonsSource).not.toContain("All checks passed.")
    expect(actionButtonsSource).not.toContain("All checks passed. Note ready to send.")
    expect(actionButtonsSource).not.toContain("Ready to decide")
    expect(actionButtonsSource).toContain("Needs attention")
    expect(actionButtonsSource).not.toContain("Pre-flight checks")
    expect(actionButtonsSource).toContain("data-action-rail-pinned")
    expect(actionButtonsSource).toContain("data-decline-lane")
    expect(actionButtonsSource).toContain("sm:order-first sm:mr-auto")
    expect(actionButtonsSource).toContain("border-border/60")
    expect(actionButtonsSource).toContain("Intake checked. Review before you send.")
    expect(actionButtonsSource).toContain("const incompleteChecks")
    expect(actionButtonsSource).toContain("data-readiness-check")
    expect(actionButtonsSource).toContain('completeLabel: "Intake checked"')
    expect(actionButtonsSource).toContain('completeLabel: "No flags detected in screener"')
    expect(actionButtonsSource).toContain('completeLabel: "Draft note ready"')
    expect(actionButtonsSource).toContain("visibleSummary")
    expect(actionButtonsSource).toContain('label: "Note ready"')
    expect(actionButtonsSource).toContain("data-action-rail-outside-scroll")
    expect(actionButtonsSource).toContain("sticky bottom-0")
    expect(intakePanelSource).toContain("showTargetState")
    expect(intakePanelSource).toContain("QUEUE_WAIT_TARGET_MINUTES")
    expect(actionButtonsSource).not.toContain("sm:basis-full")
    expect(actionButtonsSource).not.toContain('`${check.label} done`')
    expect(actionButtonsSource).toContain("h-7")
    expect(actionButtonsSource).toContain("text-destructive")
    expect(actionButtonsSource).toContain("bg-transparent")
    expect(actionButtonsSource).toContain('variant="ghost"')
    expect(actionButtonsSource).toContain("aria-keyshortcuts=\"Meta+Shift+D\"")
    expect(actionButtonsSource).not.toContain("bg-rose-500")
    expect(actionButtonsSource).not.toContain("hover:bg-rose-50")
    expect(actionButtonsSource).toContain("hover:bg-destructive/5")
    expect(actionButtonsSource).toContain("sm:justify-end")
    expect(actionButtonsSource).toContain('variant="outline"')
    expect(actionButtonsSource).not.toContain("text-white/70")
    expect(actionButtonsSource).not.toContain("text-destructive/70")
    expect(dashboardLayoutSource).toContain("Doctor console")
    expect(dashboardLayoutSource).toContain("Support console")
    expect(dashboardLayoutSource).toContain("Staff console")
    expect(actionButtonsSource).not.toContain("Patient is refunded automatically if you decline.")
    expect(actionButtonsSource).not.toContain("Decline refunds ${refundShortLabel} to the patient.")
    expect(actionButtonsSource).not.toContain("If you decline, we refund the patient and close the case")
    expect(actionButtonsSource).not.toContain("Patient is refunded and notified")
    expect(actionButtonsSource).not.toContain("Approve only when symptoms, dates, and certificate type are clinically consistent")
    expect(actionButtonsSource).not.toContain("Decline and we refund the patient automatically")
    expect(actionButtonsSource).not.toContain("Fees are automatically refunded if declined")
    expect(actionButtonsSource).not.toContain("We refund the fee if you decline")
    expect(actionButtonsSource).not.toContain("#B65F56")
    expect(read("lib/hooks/use-doctor-shortcuts.ts")).not.toContain('event.key === "a"')
    expect(actionButtonsSource).not.toContain("bg-emerald-600")
  })

  it("keeps the review pane decision controls visible before scrolling", () => {
    const cockpitSource = read("components/doctor/review/intake-review-cockpit.tsx")
    const actionSource = read("components/doctor/review/intake-action-buttons.tsx")
    const clinicalCaseReviewSource = read("components/doctor/clinical-case-review.tsx")
    const reviewPanelSource = read("components/doctor/intake-review-panel.tsx")
    const requestInfoSource = read("components/doctor/review/request-info-card.tsx")

    expect(cockpitSource).toContain("requestMoreInfoAction")
    expect(cockpitSource).toContain("symptom_clarification")
    expect(cockpitSource).toContain("No symptoms yet. Ask the patient for detail.")
    expect(cockpitSource).toContain("onRequestClinicalDetail={handleRequestClinicalDetail}")
    expect(cockpitSource).toContain("showThinMedCertWarning")
    expect(cockpitSource).toContain("requiresClinicalDetail={canRequestClinicalDetail}")
    expect(cockpitSource).not.toContain("caseReadAcknowledged")
    expect(cockpitSource).not.toContain("onFocusCapture")
    expect(cockpitSource).not.toContain("const approvalReadRequired = isApprovalReviewState && !caseReadAcknowledged")
    expect(cockpitSource).not.toContain("if (hasThinMedCertIntake)")
    expect(cockpitSource).not.toContain("Ask for detail, or decline")
    expect(cockpitSource).not.toContain("No symptoms described. Request detail before issuing.")
    expect(cockpitSource).not.toContain("Sticky bottom: action bar")
    expect(actionSource).toContain('placement?: "top" | "bottom"')
    expect(actionSource).not.toContain("approvalReadRequired")
    expect(actionSource).toContain("requiresClinicalDetail")
    expect(actionSource).not.toContain("Review the case before approving.")
    expect(actionSource).not.toContain("Waiting on symptoms from the patient.")
    expect(actionSource).toContain("Approve and send")
    expect(actionSource).toContain("medCertApproveLabel")
    expect(actionSource).toContain("medCertApproveAriaLabel")
    expect(actionSource).toContain("aria-label={medCertApproveAriaLabel}")
    expect(actionSource).toContain("Send to ${patientFirstName}")
    expect(actionSource).toContain('"Request symptoms"')
    expect(actionSource).toContain("Review and send")
    expect(actionSource).toContain("Symptoms missing; the next screen asks you to confirm before sending.")
    expect(actionSource).not.toContain("Request symptoms before approving.")
    expect(actionSource).not.toContain("Ask for symptoms first. Then you can approve.")
    expect(actionSource).toContain("bg-transparent")
    expect(actionSource).toContain("bg-background")
    expect(actionSource).toContain("text-destructive")
    expect(actionSource).not.toContain("Request detail")
    expect(actionSource).toContain("operator-action-rail")
    expect(actionSource).not.toContain("decisionGuidance")
    expect(actionSource).toContain("ActionReadinessChecks")
    expect(actionSource).toContain("data-action-readiness")
    expect(cockpitSource).toContain("data-review-body-transition")
    expect(cockpitSource).toContain("scroll-pb-32")
    expect(cockpitSource).toContain("space-y-3 pb-8")
    expect(cockpitSource).toContain("mt-3 shrink-0")
    expect(cockpitSource).toContain("review-body-in_240ms")
    const reasonOrderIndex = cockpitSource.indexOf("Reason for visit")
    const requestFactsOrderIndex = cockpitSource.indexOf("<RequestInfoCard")
    const patientContextOrderIndex = cockpitSource.indexOf("<PatientDecisionStrip", requestFactsOrderIndex)
    expect(reasonOrderIndex).toBeGreaterThan(-1)
    expect(requestFactsOrderIndex).toBeGreaterThan(reasonOrderIndex)
    expect(patientContextOrderIndex).toBeGreaterThan(requestFactsOrderIndex)
    expect(clinicalCaseReviewSource).toContain('aria-label="Draft clinical note"')
    expect(clinicalCaseReviewSource).toContain("draftNoteTextareaRef")
    expect(clinicalCaseReviewSource).toContain("focus:min-h-[150px]")
    expect(clinicalCaseReviewSource).toContain("focus:ring-2")
    // Patient-facing queue copy was removed from the doctor review header
    // (2026-06-22 declutter — essentials only). The doctor doesn't need to see
    // the message shown to the patient; it was pure noise on the review surface.
    expect(reviewPanelSource).not.toContain("patientVisibleStatus")
    expect(reviewPanelSource).not.toContain("data-patient-visible-status")
    expect(reviewPanelSource).not.toContain("formatPatientVisiblePreview")
    expect(reviewPanelSource).not.toContain("You're next.")
    expect(reviewPanelSource).not.toContain("A doctor is looking at your request now.")
    // The redundant "Case X of Y" chrome was also removed from the header.
    expect(reviewPanelSource).not.toContain("Case {caseIndex + 1} of {totalCases}")
    expect(clinicalCaseReviewSource).toContain("visibleFacts.length > 0")
    expect(clinicalCaseReviewSource).toContain('<details open className="rounded-lg bg-muted/30')
    // "Patient answers" heading was removed in the distill pass; the section now
    // uses aria-label="Request" and renders an inline dl in compact mode.
    expect(clinicalCaseReviewSource).toContain('aria-label="Request"')
    expect(clinicalCaseReviewSource).not.toContain("What the patient told us")
    expect(clinicalCaseReviewSource).not.toContain("Patient-submitted facts")
    expect(clinicalCaseReviewSource).toContain("Draft note")
    expect(clinicalCaseReviewSource).toContain("Clinical note")
    const compactNoteOrderIndex = clinicalCaseReviewSource.indexOf("{showClinicalNoteBeforeAnswers ? clinicalNoteSection : null}")
    const patientAnswersOrderIndex = clinicalCaseReviewSource.indexOf("{visibleFacts.length > 0 ? (")
    const compactNoteAfterAnswersIndex = clinicalCaseReviewSource.indexOf("{showClinicalNoteBeforeAnswers ? null : clinicalNoteSection}")
    expect(compactNoteOrderIndex).toBeGreaterThan(-1)
    expect(patientAnswersOrderIndex).toBeGreaterThan(-1)
    expect(compactNoteOrderIndex).toBeLessThan(patientAnswersOrderIndex)
    expect(compactNoteAfterAnswersIndex).toBeGreaterThan(patientAnswersOrderIndex)
    expect(clinicalCaseReviewSource).toContain("{showClinicalNoteBeforeAnswers ? null : clinicalNoteSection}")
    expect(clinicalCaseReviewSource).toContain("Pinned case facts")
    expect(clinicalCaseReviewSource).toContain("Pinned reason for visit")
    expect(clinicalCaseReviewSource).toContain("summary.patientStory")
    expect(clinicalCaseReviewSource).toContain("pinnedDraftFacts")
    expect(clinicalCaseReviewSource).toContain("textareaClassName")
    expect(clinicalCaseReviewSource).toContain("Check before you send.")
    expect(clinicalCaseReviewSource).toContain("Start your note. Press Cmd+Enter to approve.")
    expect(clinicalCaseReviewSource).toContain("focus:min-h-[150px]")
    expect(clinicalCaseReviewSource).toContain("overflow-visible")
    expect(clinicalCaseReviewSource).toContain("contentEditable")
    expect(clinicalCaseReviewSource).toContain("setDraftNoteEditableRef")
    expect(clinicalCaseReviewSource).toContain('role="textbox"')
    expect(clinicalCaseReviewSource).toContain("onDraftNoteChange?.(event.currentTarget.innerText)")
    expect(clinicalCaseReviewSource).toContain("Issue sign-off")
    expect(clinicalCaseReviewSource).toContain("signOffParts")
    expect(clinicalCaseReviewSource).not.toContain("uppercase tracking-[0.08em]")
    expect(clinicalCaseReviewSource).toContain("Saved as you type. Private until you send.")
    expect(clinicalCaseReviewSource).toContain("Add one clinical note line before signing.")
    expect(clinicalCaseReviewSource).toContain("Structured SOAP note")
    expect(clinicalCaseReviewSource).toContain("isEditableDraftNote ? parseSoapDraft")
    expect(clinicalCaseReviewSource).toContain("getSoapTextareaRows")
    expect(clinicalCaseReviewSource).toContain("minRows={compact ?")
    expect(clinicalCaseReviewSource).not.toContain("max-h-[118px]")
    expect(clinicalCaseReviewSource).toContain("COMPACT_FACT_LIMIT = 4")
    expect(clinicalCaseReviewSource).toContain("scannableFacts.slice(0, COMPACT_FACT_LIMIT)")
    expect(clinicalCaseReviewSource).toContain("isDuplicatePatientNoteFact")
    expect(clinicalCaseReviewSource).toContain('label.toLowerCase() !== "patient note"')
    expect(clinicalCaseReviewSource).not.toContain("summary.keyFacts.slice(0, 4)")
    expect(clinicalCaseReviewSource).toContain("Subjective")
    expect(clinicalCaseReviewSource).toContain("Objective")
    expect(clinicalCaseReviewSource).toContain("Assessment")
    expect(clinicalCaseReviewSource).toContain("composeSoapDraft")
    expect(clinicalCaseReviewSource).not.toContain("Auto-saves as you type.")
    expect(clinicalCaseReviewSource).not.toContain("Only you can see this note until you send.")
    expect(clinicalCaseReviewSource).not.toContain("Approving sends the cert and saves this note.")
    expect(clinicalCaseReviewSource).toContain("draftNoteSaveError && onDraftNoteSave")
    expect(clinicalCaseReviewSource).not.toContain("Save edits before making the decision.")
    expect(requestInfoSource).toContain("splitCompactReview")
    expect(requestInfoSource).toContain("showCompactRequestHeader")
  })

  it("keeps staff routes free of marketing cookie overlays", () => {
    const globalClientsSource = read("components/providers/global-deferred-clients.tsx")

    expect(globalClientsSource).toContain("AUTHENTICATED_APP_PATH_PREFIXES")
    expect(globalClientsSource).toContain('"/dashboard"')
    expect(globalClientsSource).toContain('"/admin"')
    expect(globalClientsSource).toContain('"/doctor"')
    expect(globalClientsSource).toContain("isAuthenticatedAppPath")
    expect(globalClientsSource).toContain("isPostConversionPath() || isAuthenticatedAppPath()")
    expect(globalClientsSource).toContain("shouldLoadCookieBanner")
    expect(globalClientsSource).toContain("if (allowCookieBanner)")
  })

  it("keeps complete patient states neutral while missing states stay prominent", () => {
    const decisionStripSource = read("components/doctor/patient-decision-strip.tsx")
    const profilePanelSource = read("components/doctor/patient-profile-panel.tsx")
    const patientDetailSource = read("app/doctor/patients/[id]/patient-detail-client.tsx")
    const caseSummarySource = read("lib/doctor/case-summary.ts")
    const clinicalCaseReviewSource = read("components/doctor/clinical-case-review.tsx")

    expect(decisionStripSource).not.toContain("Identity ready")
    expect(decisionStripSource).not.toContain('snapshot.completenessTone === "complete" ? "success"')
    expect(decisionStripSource).toContain("Details complete")
    expect(caseSummarySource).toContain("Note ready")
    expect(decisionStripSource).toContain("missing &&")
    expect(decisionStripSource).not.toContain("summary.actionLabel")
    expect(decisionStripSource).toContain("showPatientName")
    expect(decisionStripSource).toContain("summaryOnly")
    expect(decisionStripSource).toContain("revealIdentityByDefault")
    expect(decisionStripSource).toContain("First visit")
    expect(decisionStripSource).toContain("patientFirstName")
    expect(decisionStripSource).toContain("About ${patientFirstName}")
    expect(decisionStripSource).not.toContain('? "Patient details"')
    expect(decisionStripSource).not.toContain("Identity and notes")
    expect(decisionStripSource).toContain("Hidden ending")
    expect(decisionStripSource).toContain("Show patient identity")
    expect(decisionStripSource).toContain("renderSummaryFacts")
    // renderCompactSummaryFacts was removed in the distill pass; compact+summaryOnly
    // now renders an inline prescribing-identity section directly.
    expect(decisionStripSource).toContain("data-compact-identity-summary")
    expect(decisionStripSource).not.toContain("rounded-lg border border-border/50 bg-background/70")
    expect(decisionStripSource).toContain("line-clamp-2 max-w-full whitespace-normal break-words")
    expect(decisionStripSource).toContain('isCompact ? "text-[11px] text-slate-500/80"')
    expect(decisionStripSource).toContain("xl:grid-cols-2")
    expect(decisionStripSource).not.toContain("xl:col-span-3")
    expect(decisionStripSource).toContain('"identity"')
    expect(decisionStripSource).toContain("identifierReveal")
    expect(decisionStripSource).toContain("fetchWithCsrf")
    expect(decisionStripSource).toContain('wide ? "line-clamp-2 break-words" : "truncate"')
    expect(clinicalCaseReviewSource).toContain("hideRecommendedPlan")
    expect(clinicalCaseReviewSource).not.toContain("Looks approvable")
    expect(clinicalCaseReviewSource).not.toContain("ACTION_STYLES")
    expect(profilePanelSource).not.toContain('snapshot.completenessTone === "complete"\\n      ? "success"')
    expect(patientDetailSource).toContain('"Synced in Parchment"')
    expect(patientDetailSource).toContain("hasParchmentBlocker")
    expect(patientDetailSource).toContain("hasPrescribingIdentityBlocker")
    expect(patientDetailSource).toContain("Verify identity:")
    expect(patientDetailSource).toContain("disabled={isParchmentSyncPending || hasPrescribingIdentityBlocker}")
    expect(patientDetailSource).toContain("disabled={isPrescriptionRefreshPending || hasPrescribingIdentityBlocker}")
    expect(patientDetailSource).toContain("disabled={!canUseParchment}")
    expect(read("app/doctor/queue/queue-table.tsx")).toContain("Verify identity · Missing")
    expect(patientDetailSource).toContain('"Prescribing"')
    expect(patientDetailSource).toContain('"Latest request"')
    expect(patientDetailSource).not.toContain('"Last request"')
    expect(patientDetailSource).toContain('"Not provided"')
  })

  it("keeps the patient profile drawer as a fast reference surface", () => {
    const source = read("components/doctor/patient-profile-panel.tsx")

    expect(source).toContain('aria-label="Identity risk"')
    expect(source).toContain('aria-label="Prescribing readiness"')
    expect(source).toContain('aria-label="Latest request"')
    expect(source).toContain('aria-label="Patient timeline"')
    expect(source).toContain("Contact and identifiers")
    expect(source).not.toContain("TabsList")
  })

  it("keeps route-facing code off broad public component barrels", () => {
    const blockedBarrelPattern =
      /from\s+["']@\/components\/(?:marketing|marketing\/sections|marketing\/shared|sections|shared)["']/g
    const files = [
      ...collectSourceFiles("app"),
      ...collectSourceFiles("components"),
    ]
    const offenders = files.flatMap((file) => {
      const matches = read(file).match(blockedBarrelPattern) ?? []

      return matches.map((match) => `${file}: ${match}`)
    })

    expect(offenders).toEqual([])
  })

  it("keeps pricing content server-rendered and isolates the sticky CTA client island", () => {
    const pricingContentSource = read("app/pricing/pricing-content.tsx")
    const stickyCtaSource = read("app/pricing/pricing-sticky-cta.tsx")

    expect(pricingContentSource.startsWith('"use client"')).toBe(false)
    expect(pricingContentSource).not.toContain("framer-motion")
    expect(pricingContentSource).not.toContain("useEffect")
    expect(stickyCtaSource.startsWith('"use client"')).toBe(true)
    expect(stickyCtaSource).toContain("IntersectionObserver")
  })

  it("keeps the medical certificate landing page server-rendered with narrow client controls", () => {
    const landingSource = read("components/marketing/med-cert-landing.tsx")
    const controlsSource = read("components/marketing/med-cert-client-controls.tsx")

    expect(landingSource.startsWith('"use client"')).toBe(false)
    expect(landingSource).not.toContain("LandingPageShell")
    expect(landingSource).not.toContain("usePatientCount")
    expect(landingSource).not.toContain("useLandingAnalytics")
    expect(controlsSource.startsWith('"use client"')).toBe(true)
    expect(controlsSource).toContain("useLandingAnalytics")
    expect(controlsSource).toContain("useServiceAvailability")
    expect(controlsSource).toContain("StickyCTA")
  })

  // The reusable service funnel shell (service-funnel-page.tsx + funnel/*)
  // was deleted 2026-07-03: its only consumer was the General Consult route
  // retired 2026-05-20. The static-section hygiene checks below keep the
  // still-live shared sections covered.
  it("keeps static shared marketing sections off Framer and client-only hooks", () => {
    const staticFunnelFiles = [
      "components/marketing/sections/pricing-guide-section.tsx",
      "components/ui/section-pill.tsx",
    ]

    for (const file of staticFunnelFiles) {
      const source = read(file)
      const trimmedSource = source.trimStart()

      expect(trimmedSource.startsWith('"use client"')).toBe(false)
      expect(trimmedSource.startsWith("'use client'")).toBe(false)
      expect(source).not.toContain("framer-motion")
      expect(source).not.toContain("useReducedMotion")
      expect(source).not.toContain("motion.")
      expect(source).not.toContain("@/components/ui/button")
    }
  })

  it("keeps the FAQ accordion interactive without pulling Framer into every FAQ page", () => {
    const faqListSource = read("components/ui/faq-list.tsx")

    expect(faqListSource.trimStart().startsWith('"use client"')).toBe(true)
    expect(faqListSource).toContain("@/components/ui/accordion")
    expect(faqListSource).not.toContain("framer-motion")
    expect(faqListSource).not.toContain("useReducedMotion")
    expect(faqListSource).not.toContain("motion.")
  })

  it("keeps shared static section primitives server-rendered", () => {
    const staticSectionFiles = [
      "components/sections/comparison-table.tsx",
      "components/sections/feature-grid.tsx",
      "components/sections/icon-checklist.tsx",
      "components/sections/image-text-split.tsx",
      "components/sections/logo-badge-strip.tsx",
      "components/sections/process-steps.tsx",
      "components/sections/section-header.tsx",
      "components/sections/timeline.tsx",
    ]

    for (const file of staticSectionFiles) {
      const source = read(file)
      const trimmedSource = source.trimStart()

      expect(trimmedSource.startsWith('"use client"')).toBe(false)
      expect(trimmedSource.startsWith("'use client'")).toBe(false)
      expect(source).not.toContain("framer-motion")
      expect(source).not.toContain("useScrollReveal")
      expect(source).not.toContain("useReducedMotion")
      expect(source).not.toContain("motion.")
    }
  })
})
