/**
 * Phase 4 SEO expansion — new blog articles
 * Target: 80-100 total articles. Each 800+ words, unique content.
 */

import { Article, defaultAuthor, contentAuthors } from '../types'
import { blogImages } from '../images'

export const phase4ExpansionArticles: Article[] = [
  // Medical Certificates
  {
    slug: 'medical-certificate-jury-duty',
    title: 'Medical Certificate for Jury Duty Exemption',
    subtitle: 'When you need to be excused from jury duty due to illness or caring responsibilities.',
    excerpt: 'Summoned for jury duty but unable to serve? Learn how to get a medical certificate for jury duty exemption and what courts accept.',
    category: 'medical-certificates',
    tags: ['medical-certificate', 'jury-duty', 'court', 'exemption'],
    publishedAt: '2026-01-20',
    updatedAt: '2026-03-16',
    readingTime: 4,
    viewCount: 0,
    author: defaultAuthor,
    heroImage: blogImages.genericHealth,
    heroImageAlt: 'Legal documents and medical certificate concept',
    content: [
      {
        type: 'paragraph',
        content: 'Receiving a jury duty summons can be stressful when you have health issues or caring responsibilities. Australian courts understand that not everyone can serve, and a medical certificate is one way to support an exemption request.',
      },
      { type: 'heading', content: 'When You Might Need an Exemption', level: 2 },
      {
        type: 'list',
        content: '',
        items: [
          'You are unwell and unfit to attend court',
          'You have a medical condition that makes jury service difficult',
          'You need to care for a sick family member',
          'You have a mental health condition that would be exacerbated',
          'You have work or study commitments that cannot be deferred',
        ],
      },
      { type: 'heading', content: 'What the Certificate Should Include', level: 2 },
      {
        type: 'paragraph',
        content: 'Courts typically accept standard medical certificates that state you are unfit for jury duty. The certificate should include your name, the dates you are unfit, and the doctor\'s details. It does not need to disclose your specific condition.',
      },
      { type: 'heading', content: 'How to Submit Your Exemption', level: 2 },
      {
        type: 'paragraph',
        content: 'Each court has its own process. Your jury summons will include instructions and a deadline. Submit your exemption request and supporting documentation before the summons date. Late submissions may not be accepted.',
      },
      {
        type: 'callout',
        variant: 'info',
        content: 'Online medical certificates from AHPRA-registered doctors are commonly accepted by Australian courts. Check your specific court\'s requirements.',
      },
      { type: 'heading', content: 'Caring Responsibilities', level: 2 },
      {
        type: 'paragraph',
        content: 'If you need to care for a sick child, elderly parent, or other dependant, a carer\'s leave certificate can support your exemption. Explain the situation when completing the form.',
      },
    ],
    faqs: [
      {
        question: 'Will the court accept an online medical certificate?',
        answer: 'Yes. Certificates from AHPRA-registered doctors are commonly accepted. Court processes vary — check your summons for instructions.',
      },
      {
        question: 'When should I submit my exemption?',
        answer: 'As soon as possible and before the summons date. Courts have deadlines for exemption requests.',
      },
    ],
    relatedServices: [
      { title: 'Medical Certificate', description: 'Get a certificate for jury duty exemption', href: '/medical-certificate/jury-duty', icon: 'certificate' },
      { title: 'GP Consultation', description: 'Discuss your situation', href: '/general-consult', icon: 'consult' },
    ],
    seo: {
      title: 'Medical Certificate for Jury Duty Exemption | InstantMed',
      description: 'Need to be excused from jury duty? Learn how to get a medical certificate for jury duty exemption. Accepted by Australian courts.',
      keywords: ['jury duty medical certificate', 'jury duty exemption', 'excused from jury duty', 'jury duty sick certificate'],
    },
  },
  // Telehealth
  {
    slug: 'telehealth-first-time-guide',
    title: 'Your First Telehealth Consultation: What to Expect',
    subtitle: 'A step-by-step guide for Australians new to online doctor appointments.',
    excerpt: 'Never used telehealth before? Learn what happens during your first online doctor consultation, what to prepare, and how it differs from an in-person visit.',
    category: 'telehealth',
    tags: ['telehealth', 'first-time', 'online-doctor', 'consultation'],
    publishedAt: '2026-02-01',
    updatedAt: '2026-03-16',
    readingTime: 5,
    viewCount: 0,
    author: contentAuthors.marcusThompson,
    heroImage: blogImages.prepareForTelehealth,
    heroImageAlt: 'Person preparing for online doctor consultation',
    content: [
      {
        type: 'paragraph',
        content: 'Telehealth has become a normal part of Australian healthcare. If you haven\'t tried it yet, the process is straightforward — and often more convenient than a clinic visit.',
      },
      { type: 'heading', content: 'Before Your Consultation', level: 2 },
      {
        type: 'list',
        content: '',
        items: [
          'Have your Medicare card ready (if applicable)',
          'List your symptoms, when they started, and what makes them better or worse',
          'Note any current medications and allergies',
          'Find a quiet, private space with good internet',
          'Have your phone charged in case the doctor needs to call',
        ],
      },
      { type: 'heading', content: 'The Typical Flow', level: 2 },
      {
        type: 'paragraph',
        content: 'Many telehealth services use an asynchronous model: you complete a questionnaire, and a doctor reviews it. You may receive a message with follow-up questions or a request for a brief call. Not all services use video — some are form-based with optional phone follow-up.',
      },
      { type: 'heading', content: 'What the Doctor Needs', level: 2 },
      {
        type: 'paragraph',
        content: 'The doctor assesses your condition based on your description. Be as specific as possible. For skin conditions, a photo can help. For throat or ear issues, the doctor may recommend an in-person visit if they need to examine you.',
      },
      {
        type: 'callout',
        variant: 'tip',
        content: 'If you\'re nervous, write down your symptoms beforehand. It helps you remember everything and keeps the consultation focused.',
      },
      { type: 'heading', content: 'After Your Consultation', level: 2 },
      {
        type: 'paragraph',
        content: 'Depending on the outcome, you might receive a prescription (eScript to your phone), a medical certificate, advice, or a recommendation to see a GP in person. Follow any instructions and complete the full course of any prescribed medication.',
      },
    ],
    faqs: [
      {
        question: 'Do I need a video call?',
        answer: 'Not always. Many services use questionnaires with optional phone follow-up. Check the service\'s process before booking.',
      },
      {
        question: 'What if the doctor can\'t help online?',
        answer: 'They\'ll advise you to see a GP in person. You typically won\'t be charged the full consultation fee if they can\'t assist.',
      },
    ],
    relatedServices: [
      { title: 'Medical Certificate', description: 'Get a certificate online', href: '/medical-certificate', icon: 'certificate' },
      { title: 'GP Consultation', description: 'Start a consultation', href: '/general-consult', icon: 'consult' },
    ],
    seo: {
      title: 'First Telehealth Consultation Guide | What to Expect | InstantMed',
      description: 'New to telehealth? Learn what to expect during your first online doctor consultation in Australia. Preparation tips and what happens next.',
      keywords: ['first telehealth consultation', 'telehealth first time', 'online doctor what to expect', 'telehealth guide australia'],
    },
  },
  {
    slug: 'when-to-use-telehealth',
    title: 'When to Use Telehealth vs In-Person Care',
    subtitle: 'Making the right choice for your situation.',
    excerpt: 'Telehealth is convenient, but it\'s not right for every situation. Learn when online care makes sense and when you should see a doctor in person.',
    category: 'telehealth',
    tags: ['telehealth', 'in-person', 'when to use', 'healthcare choice'],
    publishedAt: '2026-02-05',
    updatedAt: '2026-03-16',
    readingTime: 4,
    viewCount: 0,
    author: defaultAuthor,
    heroImage: blogImages.telehealthVsInPerson,
    heroImageAlt: 'Choosing between telehealth and in-person care',
    content: [
      {
        type: 'paragraph',
        content: 'Telehealth has expanded healthcare access, but knowing when to use it versus when to see a doctor in person helps you get the right care.',
      },
      { type: 'heading', content: 'Telehealth Works Well For', level: 2 },
      {
        type: 'list',
        content: '',
        items: [
          'Medical certificates for common illnesses',
          'Prescription renewals for stable conditions',
          'Minor infections (UTI, skin, throat)',
          'Mental health support and certificates',
          'Follow-up discussions',
          'Travel health advice',
          'General health questions',
        ],
      },
      { type: 'heading', content: 'When In-Person Is Better', level: 2 },
      {
        type: 'list',
        content: '',
        items: [
          'Conditions requiring physical examination (ears, chest, abdomen)',
          'New or worsening symptoms that need assessment',
          'Injuries that need to be examined',
          'Procedures (blood tests, vaccinations, wound care)',
          'Complex or chronic conditions needing ongoing management',
          'When you feel something is seriously wrong',
        ],
      },
      {
        type: 'callout',
        variant: 'warning',
        content: 'Chest pain, difficulty breathing, severe bleeding, stroke signs, or thoughts of self-harm require emergency care. Call 000 or go to ED.',
      },
      { type: 'heading', content: 'The Grey Area', level: 2 },
      {
        type: 'paragraph',
        content: 'Some situations can start with telehealth. A doctor may assess your information and either help you online or recommend an in-person visit. There\'s no harm in starting with telehealth for non-urgent issues — the doctor will direct you if you need more.',
      },
    ],
    faqs: [
      {
        question: 'Can a telehealth doctor refer me to a specialist?',
        answer: 'Yes. If they determine you need specialist care, they can provide a referral.',
      },
      {
        question: 'What if I\'m not sure which to choose?',
        answer: 'Start with telehealth for non-urgent issues. The doctor will advise if you need to be seen in person.',
      },
    ],
    relatedServices: [
      { title: 'GP Consultation', description: 'Online or in-person guidance', href: '/general-consult', icon: 'consult' },
      { title: 'Medical Certificate', description: 'Get a certificate online', href: '/medical-certificate', icon: 'certificate' },
    ],
    seo: {
      title: 'When to Use Telehealth vs In-Person Care | InstantMed',
      description: 'Not sure whether to use telehealth or see a doctor in person? Learn when online care works and when you need a clinic visit.',
      keywords: ['when to use telehealth', 'telehealth vs in person', 'online doctor or clinic', 'telehealth when to use'],
    },
  },
  // Conditions
  {
    slug: 'burnout-vs-stress',
    title: 'Burnout vs Stress: Knowing the Difference',
    subtitle: 'Understanding when you need more than a day off.',
    excerpt: 'Stress and burnout are related but different. Learn to recognise the signs of burnout and when to seek support.',
    category: 'conditions',
    tags: ['burnout', 'stress', 'mental-health', 'workplace'],
    publishedAt: '2026-02-10',
    updatedAt: '2026-03-16',
    readingTime: 4,
    viewCount: 0,
    author: defaultAuthor,
    heroImage: blogImages.mentalHealthDay,
    heroImageAlt: 'Person experiencing work-related exhaustion',
    content: [
      {
        type: 'paragraph',
        content: 'Stress is a normal response to pressure. Burnout is what happens when stress becomes chronic and overwhelming. The distinction matters for how you respond.',
      },
      { type: 'heading', content: 'Stress: Short-Term Pressure', level: 2 },
      {
        type: 'paragraph',
        content: 'Stress is your body\'s response to demands. It can be positive (motivating you to meet a deadline) or negative (feeling overwhelmed). With rest and support, stress usually eases.',
      },
      { type: 'heading', content: 'Burnout: Chronic Exhaustion', level: 2 },
      {
        type: 'list',
        content: '',
        items: [
          'Emotional exhaustion — feeling drained and depleted',
          'Cynicism or detachment from work',
          'Reduced sense of accomplishment',
          'Physical symptoms (fatigue, sleep problems, illness)',
          'Difficulty concentrating or making decisions',
        ],
      },
      {
        type: 'callout',
        variant: 'info',
        content: 'Burnout often develops over months. A single day off may not be enough. If you recognise these signs, consider talking to a GP or psychologist.',
      },
      { type: 'heading', content: 'Taking Time Off', level: 2 },
      {
        type: 'paragraph',
        content: 'Whether you have acute stress or burnout, taking sick leave is valid. A medical certificate can document that you are unfit for work. Mental health is a legitimate reason for leave under Australian workplace law.',
      },
    ],
    faqs: [
      {
        question: 'Can I get a medical certificate for burnout?',
        answer: 'Yes. If burnout is affecting your ability to work, a doctor can issue a certificate. You don\'t need to disclose the specific diagnosis to your employer.',
      },
      {
        question: 'How long does burnout recovery take?',
        answer: 'It varies. Some people need weeks. Professional support (GP, psychologist) can help with recovery planning.',
      },
    ],
    relatedServices: [
      { title: 'Medical Certificate', description: 'Certificate for stress or burnout leave', href: '/medical-certificate', icon: 'certificate' },
      { title: 'GP Consultation', description: 'Discuss your symptoms', href: '/general-consult', icon: 'consult' },
    ],
    seo: {
      title: 'Burnout vs Stress | Knowing the Difference | InstantMed',
      description: 'Stress and burnout are different. Learn to recognise burnout signs and when to take time off. Medical certificates available for both.',
      keywords: ['burnout vs stress', 'burnout symptoms', 'stress leave certificate', 'burnout medical certificate'],
    },
  },
  {
    slug: 'acid-reflux-gerd',
    title: 'Acid Reflux & GERD: When to See a Doctor',
    subtitle: 'Understanding heartburn, reflux, and when you need treatment.',
    excerpt: 'Occasional heartburn is common. When does it become GERD, and when should you see a doctor?',
    category: 'conditions',
    tags: ['acid-reflux', 'gerd', 'heartburn', 'digestive'],
    publishedAt: '2026-02-15',
    updatedAt: '2026-03-16',
    readingTime: 4,
    viewCount: 0,
    author: defaultAuthor,
    heroImage: blogImages.reflux,
    heroImageAlt: 'Person experiencing acid reflux discomfort',
    content: [
      {
        type: 'paragraph',
        content: 'Acid reflux occurs when stomach acid flows back into the oesophagus. Occasional reflux is normal; frequent reflux may be gastro-oesophageal reflux disease (GERD).',
      },
      { type: 'heading', content: 'Symptoms', level: 2 },
      {
        type: 'list',
        content: '',
        items: [
          'Burning sensation in chest (heartburn)',
          'Regurgitation of food or sour liquid',
          'Difficulty swallowing',
          'Chest pain (always get this checked — can mimic heart problems)',
          'Chronic cough or hoarseness',
        ],
      },
      { type: 'heading', content: 'Lifestyle Changes First', level: 2 },
      {
        type: 'list',
        content: '',
        items: [
          'Avoid large meals before bed',
          'Elevate the head of your bed',
          'Identify and avoid trigger foods (spicy, fatty, caffeine, alcohol)',
          'Lose weight if overweight',
          'Don\'t lie down within 2-3 hours of eating',
        ],
      },
      { type: 'heading', content: 'When to See a Doctor', level: 2 },
      {
        type: 'list',
        content: '',
        items: [
          'Symptoms several times a week',
          'Over-the-counter antacids aren\'t helping',
          'Difficulty swallowing',
          'Unintended weight loss',
          'Chest pain (exclude heart problems)',
          'Symptoms affecting sleep or work',
        ],
      },
      {
        type: 'callout',
        variant: 'warning',
        content: 'Chest pain should always be assessed. If you have chest pain with shortness of breath, sweating, or arm pain, call 000.',
      },
    ],
    faqs: [
      {
        question: 'Can I get reflux medication online?',
        answer: 'Yes. Doctors can prescribe proton pump inhibitors (PPIs) via telehealth for appropriate cases. Severe or persistent reflux may need in-person assessment.',
      },
      {
        question: 'Is GERD serious?',
        answer: 'Untreated GERD can lead to complications. Most people manage it well with lifestyle changes and medication. See a doctor if concerned.',
      },
    ],
    relatedServices: [
      { title: 'GP Consultation', description: 'Discuss reflux symptoms', href: '/general-consult', icon: 'consult' },
      { title: 'Prescriptions', description: 'Request reflux medication', href: '/prescriptions', icon: 'prescription' },
    ],
    seo: {
      title: 'Acid Reflux & GERD | When to See a Doctor | InstantMed',
      description: 'Understanding acid reflux and GERD. When to try lifestyle changes, when to see a doctor, and treatment options.',
      keywords: ['acid reflux', 'gerd', 'heartburn treatment', 'reflux when to see doctor'],
    },
  },
  // Medications
  {
    slug: 'antibiotics-when-appropriate',
    title: 'When Are Antibiotics Appropriate?',
    subtitle: 'Understanding when you need them and when you don\'t.',
    excerpt: 'Antibiotics save lives, but overuse causes resistance. Learn when antibiotics help and when rest or other treatments are better.',
    category: 'medications',
    tags: ['antibiotics', 'infection', 'bacterial', 'viral'],
    publishedAt: '2026-02-20',
    updatedAt: '2026-03-16',
    readingTime: 4,
    viewCount: 0,
    author: defaultAuthor,
    heroImage: blogImages.antibioticsGuide,
    heroImageAlt: 'Antibiotics and responsible use concept',
    content: [
      {
        type: 'paragraph',
        content: 'Antibiotics treat bacterial infections. They don\'t work for viral infections like colds and flu. Knowing the difference helps you get the right treatment and reduces antibiotic resistance.',
      },
      { type: 'heading', content: 'When Antibiotics Help', level: 2 },
      {
        type: 'list',
        content: '',
        items: [
          'Urinary tract infections',
          'Bacterial throat infections (strep)',
          'Some skin infections',
          'Bacterial chest infections (in some cases)',
          'Ear infections (when bacterial)',
        ],
      },
      { type: 'heading', content: 'When They Don\'t Help', level: 2 },
      {
        type: 'list',
        content: '',
        items: [
          'Colds and flu (viral)',
          'Most sore throats (viral)',
          'Bronchitis (usually viral)',
          'COVID-19 (viral — antivirals may be used in some cases)',
        ],
      },
      {
        type: 'callout',
        variant: 'info',
        content: 'If you\'re prescribed antibiotics, complete the full course even if you feel better. Stopping early can allow bacteria to survive and develop resistance.',
      },
      { type: 'heading', content: 'Getting the Right Assessment', level: 2 },
      {
        type: 'paragraph',
        content: 'A doctor assesses your symptoms to determine if antibiotics are appropriate. Telehealth can work for straightforward infections like UTIs. More complex cases may need in-person examination.',
      },
    ],
    faqs: [
      {
        question: 'Can I get antibiotics online?',
        answer: 'Yes, for appropriate conditions. UTIs, some skin infections, and throat infections can be assessed via telehealth. The doctor will prescribe only when clinically appropriate.',
      },
      {
        question: 'Why won\'t my doctor give me antibiotics for a cold?',
        answer: 'Colds are viral. Antibiotics don\'t work against viruses and can cause side effects. Rest and symptom relief are the right approach.',
      },
    ],
    relatedServices: [
      { title: 'GP Consultation', description: 'Get assessed for infection', href: '/general-consult', icon: 'consult' },
      { title: 'Prescriptions', description: 'Request antibiotics if appropriate', href: '/prescriptions', icon: 'prescription' },
    ],
    seo: {
      title: 'When Are Antibiotics Appropriate? | InstantMed',
      description: 'Antibiotics treat bacterial infections, not viruses. Learn when you need them, when you don\'t, and how to use them responsibly.',
      keywords: ['when to take antibiotics', 'antibiotics appropriate', 'antibiotic resistance', 'do I need antibiotics'],
    },
  },
  // Workplace
  {
    slug: 'shift-workers-medical-certificate',
    title: 'Medical Certificates for Shift Workers',
    subtitle: 'Getting documentation when your schedule doesn\'t match clinic hours.',
    excerpt: 'Shift workers often struggle to see a doctor during business hours. Learn how telehealth makes it easier to get a medical certificate.',
    category: 'workplace-health',
    tags: ['shift-work', 'medical-certificate', 'workplace', 'telehealth'],
    publishedAt: '2026-02-25',
    updatedAt: '2026-03-16',
    readingTime: 3,
    viewCount: 0,
    author: contentAuthors.emmaWilson,
    heroImage: blogImages.returnToWork,
    heroImageAlt: 'Shift worker managing health and work',
    content: [
      {
        type: 'paragraph',
        content: 'If you work nights, weekends, or irregular hours, finding time to see a GP can be nearly impossible. Telehealth operates outside traditional clinic hours, making it easier to get the documentation you need.',
      },
      { type: 'heading', content: 'The Challenge', level: 2 },
      {
        type: 'paragraph',
        content: 'Many GPs close at 5pm or 6pm. If you work evening or night shifts, you may be asleep when clinics are open. Weekend availability is limited. Missing a shift to see a doctor can mean lost income.',
      },
      { type: 'heading', content: 'How Telehealth Helps', level: 2 },
      {
        type: 'list',
        content: '',
        items: [
          'Submit your request when it suits you — early morning, late night, or between shifts',
          'No need to travel or wait in a clinic',
          'Extended operating hours (many services run 7 days)',
          'Certificate delivered via email — no pickup required',
        ],
      },
      { type: 'heading', content: 'What You\'ll Need', level: 2 },
      {
        type: 'paragraph',
        content: 'Describe your symptoms, when they started, and how many days you need off. Include your employer\'s name if required. The doctor will assess and issue a certificate if appropriate.',
      },
    ],
    faqs: [
      {
        question: 'Will my employer accept an online certificate?',
        answer: 'Yes. Certificates from AHPRA-registered doctors are valid for all Australian employers, including shift-work industries.',
      },
      {
        question: 'Can I get a certificate at 2am?',
        answer: 'Depends on the service. Many operate extended hours. Check before submitting — you may need to wait until the next operating window for review.',
      },
    ],
    relatedServices: [
      { title: 'Medical Certificate', description: 'Get a certificate on your schedule', href: '/medical-certificate', icon: 'certificate' },
      { title: 'For Shift Workers', description: 'Learn more', href: '/for/shift-workers', icon: 'consult' },
    ],
    seo: {
      title: 'Medical Certificates for Shift Workers | InstantMed',
      description: 'Shift workers struggle to see GPs during clinic hours. Telehealth lets you get a medical certificate when it suits your schedule.',
      keywords: ['shift worker medical certificate', 'medical certificate after hours', 'sick certificate shift work', 'night shift sick leave'],
    },
  },
  // Locations
  {
    slug: 'online-doctor-gold-coast',
    title: 'Online Doctor Gold Coast',
    subtitle: 'Healthcare from anywhere on the coast.',
    excerpt: 'Looking for an online doctor on the Gold Coast? Get medical certificates, prescriptions, and consultations from Broadbeach to Coolangatta.',
    category: 'telehealth',
    tags: ['gold-coast', 'online-doctor', 'telehealth', 'queensland'],
    publishedAt: '2026-03-01',
    updatedAt: '2026-03-16',
    readingTime: 3,
    viewCount: 0,
    author: contentAuthors.oliviaNguyen,
    heroImage: blogImages.genericHealth,
    heroImageAlt: 'Gold Coast healthcare access',
    content: [
      {
        type: 'paragraph',
        content: 'The Gold Coast has a mix of locals and visitors, and doctor availability can be stretched — especially in peak season. Online doctors bring healthcare to you, whether you\'re in Surfers Paradise, Burleigh, or the hinterland.',
      },
      { type: 'heading', content: 'Services Available', level: 2 },
      {
        type: 'list',
        content: '',
        items: [
          'Medical certificates for work and study',
          'Prescription renewals and new prescriptions',
          'General health consultations',
          'eScripts to any Gold Coast pharmacy',
        ],
      },
      { type: 'heading', content: 'For Visitors', level: 2 },
      {
        type: 'paragraph',
        content: 'If you\'re visiting the Gold Coast and need a certificate for work back home, telehealth can help. You need to be 18+, in Australia, and able to provide your details. Certificates are valid for employers nationwide.',
      },
      { type: 'heading', content: 'Pharmacies', level: 2 },
      {
        type: 'paragraph',
        content: 'The Gold Coast has pharmacies in all major centres. Your eScript can be filled at any of them — just show the QR code on your phone.',
      },
    ],
    faqs: [
      {
        question: 'Can tourists get medical certificates on the Gold Coast?',
        answer: 'Yes, if you\'re 18+ and in Australia. Certificates are valid for Australian employers. International visitors should check their home country\'s requirements.',
      },
      {
        question: 'Are certificates accepted by Gold Coast employers?',
        answer: 'Yes. AHPRA-registered doctor certificates are valid for all Australian employers.',
      },
    ],
    relatedServices: [
      { title: 'Medical Certificate', description: 'Get a certificate on the Gold Coast', href: '/medical-certificate', icon: 'certificate' },
      { title: 'GP Consultation', description: 'Online consultations', href: '/general-consult', icon: 'consult' },
    ],
    seo: {
      title: 'Online Doctor Gold Coast | Telehealth | InstantMed',
      description: 'Online doctor services on the Gold Coast. Medical certificates, prescriptions, and consultations from anywhere on the coast.',
      keywords: ['online doctor gold coast', 'telehealth gold coast', 'medical certificate gold coast', 'online gp gold coast'],
    },
  },
  {
    slug: 'online-doctor-canberra',
    title: 'Online Doctor Canberra',
    subtitle: 'Healthcare for the capital.',
    excerpt: 'Canberra residents can access medical certificates, prescriptions, and consultations online — without the wait for a bulk-billing appointment.',
    category: 'telehealth',
    tags: ['canberra', 'act', 'online-doctor', 'telehealth'],
    publishedAt: '2026-03-05',
    updatedAt: '2026-03-16',
    readingTime: 3,
    viewCount: 0,
    author: contentAuthors.jamesPatel,
    heroImage: blogImages.genericHealth,
    heroImageAlt: 'Canberra healthcare access',
    content: [
      {
        type: 'paragraph',
        content: 'Canberra has a high proportion of public servants and students — and limited bulk-billing options. Telehealth offers an alternative when you need a certificate or script without a long wait.',
      },
      { type: 'heading', content: 'Why Canberrans Use Telehealth', level: 2 },
      {
        type: 'list',
        content: '',
        items: [
          'Bypass long waits for bulk-billing appointments',
          'Get certificates and scripts from home or work',
          'Useful during parliamentary sitting periods when schedules are tight',
          'Students can access care during exam periods',
        ],
      },
      { type: 'heading', content: 'Services', level: 2 },
      {
        type: 'paragraph',
        content: 'Medical certificates for work and study, prescription renewals, general consultations. eScripts can be filled at any Canberra pharmacy.',
      },
      { type: 'heading', content: 'Coverage', level: 2 },
      {
        type: 'paragraph',
        content: 'Telehealth serves all of the ACT — Civic, Belconnen, Woden, Tuggeranong, Gungahlin, and surrounds. All you need is an internet connection.',
      },
    ],
    faqs: [
      {
        question: 'Are online certificates accepted by APS employers?',
        answer: 'Yes. Certificates from AHPRA-registered doctors meet standard Commonwealth and APS requirements.',
      },
      {
        question: 'Can ANU/UC students use telehealth?',
        answer: 'Yes. Certificates are commonly accepted for special consideration. Check your institution\'s policy.',
      },
    ],
    relatedServices: [
      { title: 'Medical Certificate', description: 'Certificates for Canberra workers', href: '/medical-certificate', icon: 'certificate' },
      { title: 'GP Consultation', description: 'Online consultations', href: '/general-consult', icon: 'consult' },
    ],
    seo: {
      title: 'Online Doctor Canberra | Telehealth ACT | InstantMed',
      description: 'Online doctor services in Canberra. Medical certificates, prescriptions, and consultations for ACT residents.',
      keywords: ['online doctor canberra', 'telehealth canberra', 'medical certificate canberra', 'online gp act'],
    },
  },
  // Trust Building
  {
    slug: 'how-to-verify-online-doctor',
    title: 'How to Verify Your Online Doctor Is Legitimate',
    subtitle: 'Checking credentials and avoiding scams.',
    excerpt: 'Not all online health services are equal. Learn how to verify that your telehealth doctor is properly registered and legitimate.',
    category: 'medical-certificates',
    tags: ['ahpra', 'doctor verification', 'telehealth', 'trust'],
    publishedAt: '2026-03-10',
    updatedAt: '2026-03-16',
    readingTime: 4,
    viewCount: 0,
    author: contentAuthors.sarahChen,
    heroImage: blogImages.ahpraRegistered,
    heroImageAlt: 'Doctor verification and credentials',
    content: [
      {
        type: 'paragraph',
        content: 'When you consult a doctor online, you want to know they\'re legitimate. In Australia, the key is AHPRA registration.',
      },
      { type: 'heading', content: 'What Is AHPRA?', level: 2 },
      {
        type: 'paragraph',
        content: 'The Australian Health Practitioner Regulation Agency (AHPRA) registers all medical practitioners in Australia. Only AHPRA-registered doctors can legally practise medicine, prescribe medication, and issue medical certificates.',
      },
      { type: 'heading', content: 'How to Check', level: 2 },
      {
        type: 'list',
        content: '',
        items: [
          'Legitimate services display their doctors\' AHPRA registration',
          'You can search the AHPRA register online (ahpra.gov.au)',
          'Medical certificates should include the doctor\'s name and provider number',
          'Be wary of services that don\'t disclose who is providing care',
        ],
      },
      { type: 'heading', content: 'Red Flags', level: 2 },
      {
        type: 'list',
        content: '',
        items: [
          'No information about who the doctors are',
          'Promises of "guaranteed" certificates regardless of condition',
          'Unusually low prices that seem too good to be true',
          'Pressure to provide payment before any assessment',
          'Overseas-based "doctors" treating Australian patients',
        ],
      },
      {
        type: 'callout',
        variant: 'info',
        content: 'Reputable telehealth services use Australian-based, AHPRA-registered doctors. They assess each case clinically and may decline requests that aren\'t appropriate.',
      },
    ],
    faqs: [
      {
        question: 'Can I look up my doctor on AHPRA?',
        answer: 'Yes. The AHPRA register is public. Search by name to confirm registration status.',
      },
      {
        question: 'What if a service won\'t tell me who the doctor is?',
        answer: 'Be cautious. Legitimate services are transparent about their medical team. Your certificate will include the doctor\'s details.',
      },
    ],
    relatedServices: [
      { title: 'About InstantMed', description: 'Our doctors and approach', href: '/about', icon: 'consult' },
      { title: 'Trust', description: 'How we operate', href: '/trust', icon: 'certificate' },
    ],
    seo: {
      title: 'How to Verify Your Online Doctor Is Legitimate | InstantMed',
      description: 'Learn how to verify that your telehealth doctor is AHPRA-registered and legitimate. Red flags to watch for.',
      keywords: ['verify online doctor', 'ahpra check', 'legitimate telehealth', 'online doctor australia legitimate'],
    },
  },
  // Additional Phase 4 articles
  {
    slug: 'contraceptive-prescription-online',
    title: 'Getting a Contraceptive Prescription Online',
    subtitle: 'Birth control prescriptions via telehealth in Australia.',
    excerpt: 'Need a contraceptive prescription? Learn how telehealth can help you get birth control without a clinic visit.',
    category: 'medications',
    tags: ['contraceptive', 'birth-control', 'prescription', 'telehealth'],
    publishedAt: '2026-03-12',
    updatedAt: '2026-03-16',
    readingTime: 4,
    viewCount: 0,
    author: defaultAuthor,
    heroImage: blogImages.genericMedical,
    heroImageAlt: 'Contraceptive and prescription concept',
    content: [
      { type: 'paragraph', content: 'Contraceptive pills, patches, and rings require a prescription in Australia. Telehealth makes it easier to get a repeat or new prescription without visiting a clinic.' },
      { type: 'heading', content: 'Who Can Use Telehealth for Contraception?', level: 2 },
      { type: 'list', content: '', items: ['Existing users needing a repeat prescription', 'Those switching to a different pill', 'Some first-time users (depends on medical history)', 'People who have had a recent check-up'] },
      { type: 'heading', content: 'When In-Person Is Needed', level: 2 },
      { type: 'list', content: '', items: ['First prescription with complex medical history', 'Long-acting methods (IUD, implant) — require insertion', 'Concerns about side effects needing examination', 'Blood pressure or other monitoring required'] },
      { type: 'callout', variant: 'info', content: 'Many telehealth services can prescribe oral contraceptives. You\'ll complete a health questionnaire and the doctor will assess suitability.' },
      { type: 'heading', content: 'eScripts and Pharmacy', level: 2 },
      { type: 'paragraph', content: 'Your prescription is sent as an eScript to your phone. Take it to any Australian pharmacy to have it dispensed.' },
    ],
    faqs: [
      { question: 'Can I get the pill online without seeing a doctor?', answer: 'You still see a doctor — via telehealth. They review your information and prescribe if appropriate. No in-person visit required for many cases.' },
      { question: 'Will my pharmacy accept an eScript for contraception?', answer: 'Yes. eScripts work at any pharmacy in Australia.' },
    ],
    relatedServices: [
      { title: 'Women\'s Health', description: 'Contraception and more', href: '/request?service=consult&subtype=womens-health', icon: 'consult' },
      { title: 'Prescriptions', description: 'Request a prescription', href: '/prescriptions', icon: 'prescription' },
    ],
    seo: { title: 'Contraceptive Prescription Online | Birth Control via Telehealth | InstantMed', description: 'Get a contraceptive prescription online in Australia. Birth control via telehealth — no clinic visit required.', keywords: ['contraceptive prescription online', 'birth control telehealth', 'pill prescription online australia'] },
  },
  {
    slug: 'teachers-medical-certificate',
    title: 'Medical Certificates for Teachers',
    subtitle: 'When you need a sick certificate and can\'t get to a GP.',
    excerpt: 'Teachers have limited time for GP visits. Learn how telehealth makes it easier to get a medical certificate for work.',
    category: 'workplace-health',
    tags: ['teachers', 'medical-certificate', 'education', 'workplace'],
    publishedAt: '2026-03-13',
    updatedAt: '2026-03-16',
    readingTime: 3,
    viewCount: 0,
    author: contentAuthors.emmaWilson,
    heroImage: blogImages.universityMedCert,
    heroImageAlt: 'Teacher managing health and work',
    content: [
      { type: 'paragraph', content: 'Teachers face a particular challenge: calling in sick often means arranging relief at short notice, and finding time to see a GP during school hours is difficult.' },
      { type: 'heading', content: 'The Teacher\'s Dilemma', level: 2 },
      { type: 'paragraph', content: 'GP clinics typically operate 9am-5pm — the same hours you\'re teaching. Taking time off to see a doctor can feel like double the disruption.' },
      { type: 'heading', content: 'How Telehealth Helps', level: 2 },
      { type: 'list', content: '', items: ['Complete the form before school, during lunch, or after work', 'No need to leave home or find relief', 'Certificate delivered via email', 'Accepted by DET, Catholic, and independent schools'] },
      { type: 'heading', content: 'What Schools Accept', level: 2 },
      { type: 'paragraph', content: 'Certificates from AHPRA-registered doctors are valid for all Australian employers, including education departments and independent schools.' },
    ],
    faqs: [
      { question: 'Do education departments accept online certificates?', answer: 'Yes. Certificates from registered doctors meet standard requirements across Australian school systems.' },
      { question: 'Can I get a certificate during school holidays?', answer: 'Yes. Our service operates 8am-10pm AEST, 7 days a week.' },
    ],
    relatedServices: [
      { title: 'Medical Certificate', description: 'Get your certificate', href: '/medical-certificate', icon: 'certificate' },
      { title: 'GP Consultation', description: 'Discuss your health', href: '/general-consult', icon: 'consult' },
    ],
    seo: { title: 'Medical Certificates for Teachers | InstantMed', description: 'Teachers: get a medical certificate without leaving home. Accepted by all Australian schools. 15-minute turnaround.', keywords: ['teacher medical certificate', 'sick certificate teachers', 'education department medical certificate'] },
  },
  {
    slug: 'migraine-triggers-and-management',
    title: 'Migraine Triggers and Management',
    subtitle: 'Understanding what sets off migraines and how to manage them.',
    excerpt: 'Migraines have many triggers. Learn about common triggers, prevention strategies, and when to see a doctor.',
    category: 'conditions',
    tags: ['migraine', 'headache', 'triggers', 'management'],
    publishedAt: '2026-03-14',
    updatedAt: '2026-03-16',
    readingTime: 4,
    viewCount: 0,
    author: defaultAuthor,
    heroImage: blogImages.insomnia,
    heroImageAlt: 'Person managing migraine',
    content: [
      { type: 'paragraph', content: 'Migraines are more than headaches. They\'re often one-sided, throbbing, and come with nausea, light sensitivity, or aura. Identifying triggers can help reduce frequency.' },
      { type: 'heading', content: 'Common Triggers', level: 2 },
      { type: 'list', content: '', items: ['Stress and anxiety', 'Sleep changes (too much or too little)', 'Certain foods (chocolate, cheese, alcohol, caffeine)', 'Hormonal changes', 'Bright lights or loud noise', 'Weather changes', 'Skipping meals'] },
      { type: 'heading', content: 'Keeping a Diary', level: 2 },
      { type: 'paragraph', content: 'Tracking migraines — when they occur, what you ate, sleep, stress — can reveal patterns. Many people find 1-2 main triggers.' },
      { type: 'heading', content: 'When to See a Doctor', level: 2 },
      { type: 'list', content: '', items: ['Frequent migraines affecting work or life', 'New or changing headache pattern', 'Need for preventive medication', 'Acute treatment (triptans) not working'] },
      { type: 'callout', variant: 'emergency', content: 'Sudden severe headache ("worst of your life"), headache with fever/stiff neck, or headache after head injury — seek urgent care.' },
    ],
    faqs: [
      { question: 'Can I get a medical certificate for a migraine?', answer: 'Yes. If a migraine prevents you from working, a doctor can issue a certificate. Telehealth can assess and certify.' },
      { question: 'Can telehealth prescribe migraine medication?', answer: 'In some cases, yes. Triptans and anti-nausea medication may be prescribed via telehealth for appropriate patients.' },
    ],
    relatedServices: [
      { title: 'Medical Certificate', description: 'Certificate for migraine leave', href: '/medical-certificate', icon: 'certificate' },
      { title: 'GP Consultation', description: 'Discuss migraine management', href: '/general-consult', icon: 'consult' },
    ],
    seo: { title: 'Migraine Triggers and Management | InstantMed', description: 'Understanding migraine triggers and management. When to see a doctor and how to reduce frequency.', keywords: ['migraine triggers', 'migraine management', 'migraine prevention', 'migraine certificate'] },
  },
  {
    slug: 'online-doctor-newcastle',
    title: 'Online Doctor Newcastle',
    subtitle: 'Healthcare across the Hunter region.',
    excerpt: 'Newcastle and Hunter residents can access medical certificates, prescriptions, and consultations online.',
    category: 'telehealth',
    tags: ['newcastle', 'hunter', 'online-doctor', 'nsw'],
    publishedAt: '2026-03-15',
    updatedAt: '2026-03-16',
    readingTime: 3,
    viewCount: 0,
    author: contentAuthors.jamesPatel,
    heroImage: blogImages.genericHealth,
    heroImageAlt: 'Newcastle healthcare access',
    content: [
      { type: 'paragraph', content: 'Newcastle and the Hunter Valley face long waits for same-day GP appointments. Telehealth offers an alternative when you need a certificate or script without the drive or the wait.' },
      { type: 'heading', content: 'Services', level: 2 },
      { type: 'list', content: '', items: ['Medical certificates for work and study', 'Prescription renewals', 'General consultations', 'eScripts to any Hunter pharmacy'] },
      { type: 'heading', content: 'Coverage', level: 2 },
      { type: 'paragraph', content: 'From Merewether to Maitland, Cessnock to Port Stephens — telehealth serves the whole Hunter region. All you need is an internet connection.' },
    ],
    faqs: [
      { question: 'Are certificates accepted by Newcastle employers?', answer: 'Yes. AHPRA-registered doctor certificates are valid for all Australian employers.' },
      { question: 'Can I use this in regional Hunter towns?', answer: 'Yes. Telehealth works anywhere in Australia with internet access.' },
    ],
    relatedServices: [
      { title: 'Medical Certificate', description: 'Get a certificate', href: '/medical-certificate', icon: 'certificate' },
      { title: 'GP Consultation', description: 'Online consultations', href: '/general-consult', icon: 'consult' },
    ],
    seo: { title: 'Online Doctor Newcastle | Hunter Region Telehealth | InstantMed', description: 'Online doctor services in Newcastle and the Hunter. Medical certificates and prescriptions without the wait.', keywords: ['online doctor newcastle', 'telehealth newcastle', 'medical certificate newcastle', 'hunter region doctor'] },
  },
  {
    slug: 'medical-certificate-bereavement',
    title: 'Medical Certificate for Bereavement Leave',
    subtitle: 'Documentation when you need time off after a loss.',
    excerpt: 'Bereavement leave is a workplace entitlement. Learn when you might need a medical certificate and what employers can ask.',
    category: 'medical-certificates',
    tags: ['bereavement', 'grief', 'medical-certificate', 'workplace'],
    publishedAt: '2026-03-15',
    updatedAt: '2026-03-16',
    readingTime: 3,
    viewCount: 0,
    author: contentAuthors.emmaWilson,
    heroImage: blogImages.certificateDuration,
    heroImageAlt: 'Bereavement and workplace support',
    content: [
      { type: 'paragraph', content: 'Bereavement leave allows time off after the death of a family member or close relation. Most employers offer 2-5 days paid leave. Some may request documentation.' },
      { type: 'heading', content: 'When a Certificate Might Be Needed', level: 2 },
      { type: 'paragraph', content: 'Standard bereavement leave usually doesn\'t require a medical certificate. However, if you need extended leave due to grief affecting your ability to work, a doctor can provide documentation.' },
      { type: 'heading', content: 'Grief and Mental Health', level: 2 },
      { type: 'paragraph', content: 'Prolonged grief can affect mental health. If you\'re unable to work due to the impact of a loss, a medical certificate can support additional leave. This is typically personal/carer\'s leave or unpaid leave.' },
      { type: 'callout', variant: 'info', content: 'Check your employment agreement for bereavement leave entitlements. Requirements vary by employer and award.' },
    ],
    faqs: [
      { question: 'Do I need a certificate for standard bereavement leave?', answer: 'Usually no. Most employers don\'t require documentation for the standard 2-5 days. Check your workplace policy.' },
      { question: 'Can I get a certificate for extended grief leave?', answer: 'Yes. If grief is affecting your ability to work, a doctor can assess and issue a certificate for additional time off.' },
    ],
    relatedServices: [
      { title: 'Medical Certificate', description: 'Certificate if needed', href: '/medical-certificate', icon: 'certificate' },
      { title: 'GP Consultation', description: 'Discuss your situation', href: '/general-consult', icon: 'consult' },
    ],
    seo: { title: 'Medical Certificate for Bereavement Leave | InstantMed', description: 'Bereavement leave and medical certificates. When you might need documentation for extended grief leave.', keywords: ['bereavement leave certificate', 'grief leave medical certificate', 'bereavement documentation'] },
  },
  {
    slug: 'telehealth-record-keeping',
    title: 'Telehealth and Medical Record Keeping',
    subtitle: 'What happens to your health information when you use telehealth.',
    excerpt: 'Understanding how telehealth services handle your medical records, privacy, and continuity of care.',
    category: 'telehealth',
    tags: ['telehealth', 'privacy', 'records', 'medical-history'],
    publishedAt: '2026-03-16',
    updatedAt: '2026-03-16',
    readingTime: 4,
    viewCount: 0,
    author: contentAuthors.sarahChen,
    heroImage: blogImages.telehealthPrivacy,
    heroImageAlt: 'Medical records and privacy',
    content: [
      { type: 'paragraph', content: 'When you use telehealth, your health information is recorded — just like an in-person visit. Understanding how records are kept helps you make informed choices.' },
      { type: 'heading', content: 'What Gets Recorded', level: 2 },
      { type: 'list', content: '', items: ['Your symptoms and history', 'The doctor\'s assessment', 'Prescriptions issued', 'Certificates issued', 'Any advice or recommendations'] },
      { type: 'heading', content: 'Privacy and Security', level: 2 },
      { type: 'paragraph', content: 'Reputable telehealth services use encrypted systems and comply with Australian privacy law. Your information is not shared with employers, insurers, or third parties without your consent.' },
      { type: 'heading', content: 'Continuity with Your GP', level: 2 },
      { type: 'paragraph', content: 'Telehealth providers may offer to send a summary to your regular GP. This helps with continuity. You can also request your records if you need them for another provider.' },
      { type: 'callout', variant: 'tip', content: 'If you have a regular GP, consider sharing telehealth summaries so they have a complete picture of your care.' },
    ],
    faqs: [
      { question: 'Can my employer see my telehealth records?', answer: 'No. Medical records are confidential. Your employer only sees what you provide — such as a certificate — not your full medical history.' },
      { question: 'How long are records kept?', answer: 'Australian law requires medical records to be kept for at least 7 years (or until the patient turns 25 for paediatric records).' },
    ],
    relatedServices: [
      { title: 'Privacy Policy', description: 'How we handle your data', href: '/privacy', icon: 'consult' },
      { title: 'Trust', description: 'Our approach to care', href: '/trust', icon: 'certificate' },
    ],
    seo: { title: 'Telehealth and Medical Record Keeping | InstantMed', description: 'How telehealth services handle your medical records, privacy, and continuity of care in Australia.', keywords: ['telehealth records', 'medical record privacy', 'telehealth privacy australia'] },
  },
  {
    slug: 'parents-sick-child-certificate',
    title: 'Medical Certificates When Your Child Is Sick',
    subtitle: 'Documentation for school absences and carer\'s leave.',
    excerpt: 'When your child is sick, you may need a certificate for school or work. Learn how telehealth can help.',
    category: 'workplace-health',
    tags: ['parents', 'children', 'carers-leave', 'school-absence'],
    publishedAt: '2026-03-16',
    updatedAt: '2026-03-16',
    readingTime: 4,
    viewCount: 0,
    author: defaultAuthor,
    heroImage: blogImages.carersLeave,
    heroImageAlt: 'Parent caring for sick child',
    content: [
      { type: 'paragraph', content: 'When your child is unwell, you may need to take carer\'s leave — and sometimes the school or your employer wants documentation.' },
      { type: 'heading', content: 'Carer\'s Leave for Work', level: 2 },
      { type: 'paragraph', content: 'If you need to stay home to care for a sick child, you can use carer\'s leave. Your employer may request a medical certificate. The certificate documents that your child needed care, not your own illness.' },
      { type: 'heading', content: 'School Absence Certificates', level: 2 },
      { type: 'paragraph', content: 'Some schools request a medical certificate for absences. You complete the form on behalf of your child. The doctor may need a brief call to confirm details for paediatric cases.' },
      { type: 'heading', content: 'How Telehealth Helps', level: 2 },
      { type: 'paragraph', content: 'You don\'t need to take a sick child to a clinic to get a certificate. Describe their symptoms, and a doctor can issue documentation if appropriate. Useful when they\'re contagious or too unwell to travel.' },
      { type: 'callout', variant: 'warning', content: 'If your child has severe symptoms, difficulty breathing, or you\'re concerned, seek in-person care. Telehealth is for documentation, not replacing paediatric assessment when needed.' },
    ],
    faqs: [
      { question: 'Can I get a certificate for my child\'s school absence?', answer: 'Yes. You complete the form on behalf of your child. The doctor assesses and may issue a certificate. Some services may request a brief call for paediatric cases.' },
      { question: 'Does the certificate go to the school or my employer?', answer: 'You receive the certificate and forward it to whoever needs it — school, employer, or both.' },
    ],
    relatedServices: [
      { title: 'Medical Certificate', description: 'Carer\'s leave and school absence', href: '/medical-certificate/carer', icon: 'certificate' },
      { title: 'GP Consultation', description: 'Discuss your child\'s health', href: '/general-consult', icon: 'consult' },
    ],
    seo: { title: 'Medical Certificates When Your Child Is Sick | InstantMed', description: 'Get a medical certificate for carer\'s leave or school absence when your child is sick. No need to take them to a clinic.', keywords: ['sick child medical certificate', 'carers leave certificate', 'school absence certificate child'] },
  },
  {
    slug: 'remote-workers-telehealth',
    title: 'Telehealth for Remote Workers',
    subtitle: 'Healthcare when you work from home or regionally.',
    excerpt: 'Remote workers often lack easy access to a local GP. Telehealth brings healthcare to you wherever you are.',
    category: 'telehealth',
    tags: ['remote-work', 'telehealth', 'work-from-home', 'regional'],
    publishedAt: '2026-03-16',
    updatedAt: '2026-03-16',
    readingTime: 3,
    viewCount: 0,
    author: contentAuthors.marcusThompson,
    heroImage: blogImages.workFromHomeSick,
    heroImageAlt: 'Remote worker accessing healthcare',
    content: [
      { type: 'paragraph', content: 'Whether you work from home in the city or live regionally, getting to a GP can be inconvenient. Telehealth fits around your schedule and location.' },
      { type: 'heading', content: 'Benefits for Remote Workers', level: 2 },
      { type: 'list', content: '', items: ['No commute to a clinic', 'Fit consultations into your day', 'Useful when you\'re unwell but not bed-bound', 'Same quality care, more convenience', 'eScripts to any pharmacy — including regional'] },
      { type: 'heading', content: 'Regional Australia', level: 2 },
      { type: 'paragraph', content: 'Telehealth is especially valuable in regional areas where GP availability is limited. You get access to Australian doctors without the drive to the nearest town.' },
      { type: 'heading', content: 'Medical Certificates', level: 2 },
      { type: 'paragraph', content: 'Working from home doesn\'t mean you can\'t take sick leave. If you\'re unwell, you\'re entitled to it. Telehealth makes it easy to get the documentation your employer needs.' },
    ],
    faqs: [
      { question: 'Can I use telehealth if I live regionally?', answer: 'Yes. Telehealth works anywhere in Australia with internet access. It\'s designed to improve access in underserved areas.' },
      { question: 'Do I need a local GP for telehealth?', answer: 'No. Telehealth connects you with Australian doctors regardless of your location. You can use it alongside or instead of a local GP.' },
    ],
    relatedServices: [
      { title: 'Medical Certificate', description: 'Get a certificate from home', href: '/medical-certificate', icon: 'certificate' },
      { title: 'GP Consultation', description: 'Online consultations', href: '/general-consult', icon: 'consult' },
    ],
    seo: { title: 'Telehealth for Remote Workers | InstantMed', description: 'Remote workers: access healthcare from anywhere. Medical certificates, prescriptions, and consultations without leaving home.', keywords: ['remote worker telehealth', 'work from home doctor', 'telehealth regional australia'] },
  },
]
