/**
 * Zod schema for AI-generated clinical note output
 * 
 * Validates the structure of clinical notes generated by the AI model.
 * Used to catch malformed JSON and ensure consistent output.
 */

import { z } from "zod"

export const ClinicalNoteOutputSchema = z.object({
  presentingComplaint: z.string().min(1, "Presenting complaint is required"),
  historyOfPresentIllness: z.string().min(1, "History is required"),
  relevantInformation: z.string().optional().default(""),
  certificateDetails: z.string().optional().default(""),
  flags: z.object({
    requiresReview: z.boolean().default(false),
    flagReason: z.string().nullable().default(null),
  }).optional().default({ requiresReview: false, flagReason: null }),
})

export type ClinicalNoteOutput = z.infer<typeof ClinicalNoteOutputSchema>

/**
 * Parse and validate raw AI output for clinical note
 * Returns validated output or throws ZodError
 */
export function parseClinicalNoteOutput(rawOutput: string): ClinicalNoteOutput {
  // Try to extract JSON from the response (AI may wrap in markdown)
  let jsonString = rawOutput.trim()
  
  // Remove markdown code fences if present
  const jsonMatch = jsonString.match(/```(?:json)?\s*([\s\S]*?)\s*```/)
  if (jsonMatch) {
    jsonString = jsonMatch[1].trim()
  }
  
  // Parse JSON
  const parsed = JSON.parse(jsonString)
  
  // Validate with Zod
  return ClinicalNoteOutputSchema.parse(parsed)
}

/**
 * Safe parse that returns result object instead of throwing
 */
export function safeParseClinicalNoteOutput(rawOutput: string): {
  success: boolean
  data?: ClinicalNoteOutput
  error?: string
  zodErrors?: z.ZodIssue[]
} {
  try {
    const data = parseClinicalNoteOutput(rawOutput)
    return { success: true, data }
  } catch (error) {
    if (error instanceof z.ZodError) {
      return {
        success: false,
        error: "Validation failed",
        zodErrors: error.issues,
      }
    }
    if (error instanceof SyntaxError) {
      return {
        success: false,
        error: `Invalid JSON: ${error.message}`,
      }
    }
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    }
  }
}
