/**
 * Zod schema for AI-generated consultation draft output
 * 
 * Validates the structure of consult drafts generated by the AI model.
 * Used to catch malformed JSON and ensure consistent output.
 */

import { z } from "zod"

export const ConsultDraftOutputSchema = z.object({
  chiefComplaint: z.string().min(1, "Chief complaint is required"),
  historyOfPresentIllness: z.string().min(1, "History is required"),
  relevantHistory: z.string().optional().default(""),
  systemsReview: z.string().optional().default(""),
  urgencyAssessment: z.enum(["routine", "soon", "urgent"]).default("routine"),
  suggestedConsultType: z.enum(["async", "phone", "video"]).default("async"),
  clinicalConsiderations: z.string().optional().default(""),
  flags: z.object({
    requiresReview: z.boolean().default(false),
    flagReason: z.string().nullable().default(null),
    urgentConcern: z.boolean().default(false),
    mentalHealthFlag: z.boolean().default(false),
  }).optional().default({ 
    requiresReview: false, 
    flagReason: null,
    urgentConcern: false,
    mentalHealthFlag: false,
  }),
})

export type ConsultDraftOutput = z.infer<typeof ConsultDraftOutputSchema>

/**
 * Parse and validate raw AI output for consult draft
 * Returns validated output or throws ZodError
 */
export function parseConsultDraftOutput(rawOutput: string): ConsultDraftOutput {
  // Try to extract JSON from the response (AI may wrap in markdown)
  let jsonString = rawOutput.trim()
  
  // Remove markdown code fences if present
  const jsonMatch = jsonString.match(/```(?:json)?\s*([\s\S]*?)\s*```/)
  if (jsonMatch) {
    jsonString = jsonMatch[1].trim()
  }
  
  // Parse JSON
  const parsed = JSON.parse(jsonString)
  
  // Validate with Zod
  return ConsultDraftOutputSchema.parse(parsed)
}

/**
 * Safe parse that returns result object instead of throwing
 */
export function safeParseConsultDraftOutput(rawOutput: string): {
  success: boolean
  data?: ConsultDraftOutput
  error?: string
  zodErrors?: z.ZodIssue[]
} {
  try {
    const data = parseConsultDraftOutput(rawOutput)
    return { success: true, data }
  } catch (error) {
    if (error instanceof z.ZodError) {
      return {
        success: false,
        error: "Validation failed",
        zodErrors: error.issues,
      }
    }
    if (error instanceof SyntaxError) {
      return {
        success: false,
        error: `Invalid JSON: ${error.message}`,
      }
    }
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    }
  }
}
