/**
 * Zod schema for AI-generated medical certificate draft output
 * 
 * Validates the structure of med cert drafts generated by the AI model.
 * Used to catch malformed JSON and ensure consistent output.
 */

import { z } from "zod"

export const MedCertDraftOutputSchema = z.object({
  certificateStatement: z.string().min(10, "Certificate statement is required"),
  symptomsSummary: z.string().min(1, "Symptoms summary is required"),
  clinicalNotes: z.string().optional().default(""),
  startDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Start date must be YYYY-MM-DD"),
  endDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "End date must be YYYY-MM-DD"),
  durationDays: z.number().int().min(1).max(14),
  certificateType: z.enum(["work", "study", "carer"]),
  flags: z.object({
    requiresReview: z.boolean().default(false),
    flagReason: z.string().nullable().default(null),
  }).optional().default({ requiresReview: false, flagReason: null }),
})

export type MedCertDraftOutput = z.infer<typeof MedCertDraftOutputSchema>

/**
 * Parse and validate raw AI output for med cert draft
 * Returns validated output or throws ZodError
 */
export function parseMedCertDraftOutput(rawOutput: string): MedCertDraftOutput {
  // Try to extract JSON from the response (AI may wrap in markdown)
  let jsonString = rawOutput.trim()
  
  // Remove markdown code fences if present
  const jsonMatch = jsonString.match(/```(?:json)?\s*([\s\S]*?)\s*```/)
  if (jsonMatch) {
    jsonString = jsonMatch[1].trim()
  }
  
  // Parse JSON
  const parsed = JSON.parse(jsonString)
  
  // Validate with Zod
  return MedCertDraftOutputSchema.parse(parsed)
}

/**
 * Safe parse that returns result object instead of throwing
 */
export function safeParseMedCertDraftOutput(rawOutput: string): {
  success: boolean
  data?: MedCertDraftOutput
  error?: string
  zodErrors?: z.ZodIssue[]
} {
  try {
    const data = parseMedCertDraftOutput(rawOutput)
    return { success: true, data }
  } catch (error) {
    if (error instanceof z.ZodError) {
      return {
        success: false,
        error: "Validation failed",
        zodErrors: error.issues,
      }
    }
    if (error instanceof SyntaxError) {
      return {
        success: false,
        error: `Invalid JSON: ${error.message}`,
      }
    }
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    }
  }
}
