/**
 * Zod schema for AI-generated repeat prescription draft output
 * 
 * Validates the structure of repeat rx drafts generated by the AI model.
 * Used to catch malformed JSON and ensure consistent output.
 */

import { z } from "zod"

export const RepeatRxDraftOutputSchema = z.object({
  medicationSummary: z.string().min(1, "Medication summary is required"),
  indicationStatement: z.string().min(1, "Indication statement is required"),
  treatmentHistory: z.string().optional().default(""),
  complianceNotes: z.string().optional().default(""),
  clinicalConsiderations: z.string().optional().default(""),
  flags: z.object({
    requiresReview: z.boolean().default(false),
    flagReason: z.string().nullable().default(null),
    controlledSubstance: z.boolean().default(false),
    interactionRisk: z.boolean().default(false),
  }).optional().default({ 
    requiresReview: false, 
    flagReason: null,
    controlledSubstance: false,
    interactionRisk: false,
  }),
})

export type RepeatRxDraftOutput = z.infer<typeof RepeatRxDraftOutputSchema>

/**
 * Parse and validate raw AI output for repeat rx draft
 * Returns validated output or throws ZodError
 */
export function parseRepeatRxDraftOutput(rawOutput: string): RepeatRxDraftOutput {
  // Try to extract JSON from the response (AI may wrap in markdown)
  let jsonString = rawOutput.trim()
  
  // Remove markdown code fences if present
  const jsonMatch = jsonString.match(/```(?:json)?\s*([\s\S]*?)\s*```/)
  if (jsonMatch) {
    jsonString = jsonMatch[1].trim()
  }
  
  // Parse JSON
  const parsed = JSON.parse(jsonString)
  
  // Validate with Zod
  return RepeatRxDraftOutputSchema.parse(parsed)
}

/**
 * Safe parse that returns result object instead of throwing
 */
export function safeParseRepeatRxDraftOutput(rawOutput: string): {
  success: boolean
  data?: RepeatRxDraftOutput
  error?: string
  zodErrors?: z.ZodIssue[]
} {
  try {
    const data = parseRepeatRxDraftOutput(rawOutput)
    return { success: true, data }
  } catch (error) {
    if (error instanceof z.ZodError) {
      return {
        success: false,
        error: "Validation failed",
        zodErrors: error.issues,
      }
    }
    if (error instanceof SyntaxError) {
      return {
        success: false,
        error: `Invalid JSON: ${error.message}`,
      }
    }
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    }
  }
}
