-- Add columns for AI draft tracking on document_drafts
-- The code uses intake_id but table has request_id - add intake_id as alias/reference

ALTER TABLE public.document_drafts
ADD COLUMN IF NOT EXISTS intake_id uuid REFERENCES public.intakes(id),
ADD COLUMN IF NOT EXISTS is_ai_generated boolean DEFAULT false;

-- Add index for efficient lookup by intake_id
CREATE INDEX IF NOT EXISTS idx_document_drafts_intake_id 
ON public.document_drafts(intake_id) 
WHERE intake_id IS NOT NULL;

-- Add index for AI-generated drafts
CREATE INDEX IF NOT EXISTS idx_document_drafts_ai_generated 
ON public.document_drafts(intake_id, is_ai_generated) 
WHERE is_ai_generated = true;

COMMENT ON COLUMN public.document_drafts.intake_id IS 'Reference to intake for AI-generated drafts';
COMMENT ON COLUMN public.document_drafts.is_ai_generated IS 'Whether this draft was generated by AI';
