// Centralized exports for all shared UI components
// Import from '@/components/ui' instead of individual files

export * from './accordion'
export * from './alert'
export * from './alert-dialog'
export * from './avatar'
export * from './badge'
export * from './button'
export * from './calendar'
export * from './card'
export * from './checkbox'
export * from './collapsible'
export * from './dialog'
export * from './dropdown-menu'
export * from './input'
export * from './label'
export * from './loading-spinner'
export * from './modal'
export * from './popover'
export * from './progress'
export * from './radio-group'
export * from './scroll-area'
export * from './select'
export * from './separator'
export * from './skeleton'
export * from './switch'
export * from './table'
export * from './tabs'
export * from './textarea'
export * from './toggle'
export * from './tooltip'

// UX Components
export * from './empty-state'
export * from './page-loading'
export * from './error-boundary'
export * from './form-persistence'
export * from './toast-provider'

// Note: Toaster is exported separately as it needs to be placed at root
// import { Toaster } from '@/components/ui/sonner'
